In [ ]:
!pip install datasets==3.6.0 --q

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 491.5/491.5 kB 9.5 MB/s eta 0:00:00

In [ ]:
!pip install datasets==2.19.0 --q

In [ ]:
import pandas as pd
import torch
from datasets import load_dataset
import transformers
from transformers import AutoTokenizer, AutoConfig, AutoModel

### Loading a dataset

In [ ]:
dataset = load_dataset(
    "emarro/clinvar_vep_512",
    split="test"
    )

README.md:   0%|          | 0.00/744 [00:00<?, ?B/s]

data/train-00000-of-00001.parquet:   0%|          | 0.00/21.0M [00:00<?, ?B/s]

data/test-00000-of-00001.parquet:   0%|          | 0.00/644k [00:00<?, ?B/s]

Generating train split:   0%|          | 0/38634 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/1018 [00:00<?, ? examples/s]

In [ ]:
print(dataset)

Dataset({
    features: ['ref_forward_sequence', 'alt_forward_sequence', 'label', 'chromosome', 'position', 'seq', 'ref', 'alt', 'start', 'stop', 'chrom'],
    num_rows: 1018
})

In [ ]:
df = pd.DataFrame(dataset)
df.head()

,ref_forward_sequence,alt_forward_sequence,label,chromosome,position,seq,ref,alt,start,stop,chrom
0,ACTGGGGTAGTGATGTGTCCTTGTTTCTATCGAGTCAACACAAAAT...,ACTGGGGTAGTGATGTGTCCTTGTTTCTATCGAGTCAACACAAAAT...,1,8,1771124,ACTGGGGTAGTGATGTGTCCTTGTTTCTATCGAGTCAACACAAAAT...,C,G,1771124,1771636,8
1,CCTTGTTTCTATCGAGTCAACACAAAATGAATGATCTTTCTTTTAG...,CCTTGTTTCTATCGAGTCAACACAAAATGAATGATCTTTCTTTTAG...,1,8,1771142,CCTTGTTTCTATCGAGTCAACACAAAATGAATGATCTTTCTTTTAG...,G,C,1771142,1771654,8
2,TCTCCATGCAGGCGGGCTGGTCCGAGTCTCTGTTTTGGAAGCTCAA...,TCTCCATGCAGGCGGGCTGGTCCGAGTCTCTGTTTTGGAAGCTCAA...,1,8,1780495,TCTCCATGCAGGCGGGCTGGTCCGAGTCTCTGTTTTGGAAGCTCAA...,G,C,1780495,1781007,8
3,GGGAACATGTTTCACCATGTCCAGGAAGGGCTGTATTTTTAAGGTC...,GGGAACATGTTTCACCATGTCCAGGAAGGGCTGTATTTTTAAGGTC...,1,8,1882669,GGGAACATGTTTCACCATGTCCAGGAAGGGCTGTATTTTTAAGGTC...,C,T,1882669,1883181,8
4,TAACACTTCAGAGGGTTTTTAGAGGGAGTAGATGTGAACTTGTGTG...,TAACACTTCAGAGGGTTTTTAGAGGGAGTAGATGTGAACTTGTGTG...,1,8,6414797,TAACACTTCAGAGGGTTTTTAGAGGGAGTAGATGTGAACTTGTGTG...,C,G,6414797,6415309,8

### Loading and manipulating a dataset
https://huggingface.co/datasets/InstaDeepAI/nucleotide_transformer_downstream_tasks_revised

In [ ]:
dataset = load_dataset("InstaDeepAI/nucleotide_transformer_downstream_tasks_revised")
print(dataset)

Resolving data files:   0%|          | 0/18 [00:00<?, ?it/s]

Resolving data files:   0%|          | 0/18 [00:00<?, ?it/s]

Downloading data:   0%|          | 0/18 [00:00<?, ?files/s]

promoter_all/train.parquet:   0%|          | 0.00/4.83M [00:00<?, ?B/s]

enhancers_types/train.parquet:   0%|          | 0.00/6.22M [00:00<?, ?B/s]

H3K27me3/train.parquet:   0%|          | 0.00/14.6M [00:00<?, ?B/s]

H3K27ac/train.parquet:   0%|          | 0.00/14.6M [00:00<?, ?B/s]

H3K4me2/train.parquet:   0%|          | 0.00/14.6M [00:00<?, ?B/s]

H4K20me1/train.parquet:   0%|          | 0.00/14.6M [00:00<?, ?B/s]

H3K4me3/train.parquet:   0%|          | 0.00/8.44M [00:00<?, ?B/s]

promoter_tata/train.parquet:   0%|          | 0.00/811k [00:00<?, ?B/s]

H3K9ac/train.parquet:   0%|          | 0.00/11.3M [00:00<?, ?B/s]

H3K36me3/train.parquet:   0%|          | 0.00/14.5M [00:00<?, ?B/s]

H2AFZ/train.parquet:   0%|          | 0.00/14.6M [00:00<?, ?B/s]

enhancers/train.parquet:   0%|          | 0.00/6.21M [00:00<?, ?B/s]

splice_sites_acceptors/train.parquet:   0%|          | 0.00/9.01M [00:00<?, ?B/s]

H3K4me1/train.parquet:   0%|          | 0.00/14.6M [00:00<?, ?B/s]

promoter_no_tata/train.parquet:   0%|          | 0.00/4.83M [00:00<?, ?B/s]

H3K9me3/train.parquet:   0%|          | 0.00/13.2M [00:00<?, ?B/s]

splice_sites_all/train.parquet:   0%|          | 0.00/9.06M [00:00<?, ?B/s]

splice_sites_donors/train.parquet:   0%|          | 0.00/9.02M [00:00<?, ?B/s]

Downloading data:   0%|          | 0/18 [00:00<?, ?files/s]

H3K27me3/test.parquet:   0%|          | 0.00/1.45M [00:00<?, ?B/s]

H3K27ac/test.parquet:   0%|          | 0.00/779k [00:00<?, ?B/s]

H2AFZ/test.parquet:   0%|          | 0.00/1.45M [00:00<?, ?B/s]

H3K36me3/test.parquet:   0%|          | 0.00/1.44M [00:00<?, ?B/s]

enhancers_types/test.parquet:   0%|          | 0.00/610k [00:00<?, ?B/s]

H3K9ac/test.parquet:   0%|          | 0.00/487k [00:00<?, ?B/s]

H3K4me2/test.parquet:   0%|          | 0.00/1.03M [00:00<?, ?B/s]

promoter_no_tata/test.parquet:   0%|          | 0.00/219k [00:00<?, ?B/s]

H3K9me3/test.parquet:   0%|          | 0.00/411k [00:00<?, ?B/s]

H3K4me3/test.parquet:   0%|          | 0.00/378k [00:00<?, ?B/s]

promoter_tata/test.parquet:   0%|          | 0.00/37.5k [00:00<?, ?B/s]

H4K20me1/test.parquet:   0%|          | 0.00/1.09M [00:00<?, ?B/s]

H3K4me1/test.parquet:   0%|          | 0.00/1.45M [00:00<?, ?B/s]

enhancers/test.parquet:   0%|          | 0.00/610k [00:00<?, ?B/s]

splice_sites_acceptors/test.parquet:   0%|          | 0.00/894k [00:00<?, ?B/s]

promoter_all/test.parquet:   0%|          | 0.00/252k [00:00<?, ?B/s]

splice_sites_donors/test.parquet:   0%|          | 0.00/894k [00:00<?, ?B/s]

splice_sites_all/test.parquet:   0%|          | 0.00/903k [00:00<?, ?B/s]

Generating train split:   0%|          | 0/493242 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/38822 [00:00<?, ? examples/s]

DatasetDict({
    train: Dataset({
        features: ['sequence', 'name', 'label', 'task'],
        num_rows: 493242
    })
    test: Dataset({
        features: ['sequence', 'name', 'label', 'task'],
        num_rows: 38822
    })
})

This gives us a Huggingface DatasetDict, containing two Huggingface Dataset objects, one for the train and one for the test split.

In [ ]:
train_dataset = dataset["train"]
print(train_dataset)

Dataset({
    features: ['sequence', 'name', 'label', 'task'],
    num_rows: 493242
})

A Huggingface Dataset can be converted into a Pandas DataFrame.

In [ ]:
train_df = train_dataset.to_pandas()
train_df.head()

,sequence,name,label,task
0,ATATTTTTCGGTGTTTTTTTAAAATCCAGAAAAGGTTAATTGTTTT...,chr8:16774000-16775000|0,0,H2AFZ
1,AAGTATAGTCATAAAGGTGGGGGATTTAATCATGTTCCAGAATGAT...,chr12:12784548-12785548|1,1,H2AFZ
2,CCCCAGCATGGACTTGCAGGGGCGCCTGGTGGGAGAGGGGTGTGGA...,chr1:1376174-1377174|1,1,H2AFZ
3,GCCTGTAATCCCAGCACTTTGAGAGGCCGGGGCGGGCAGATCACGA...,chr17:78711000-78712000|0,0,H2AFZ
4,CTGCGGCTTTTGGAGGGAGCTTGGCTTGGAACCCAGGGTTCTCTGA...,chr8:127981888-127982888|1,1,H2AFZ

You can then do all the usual Pandas manipulations, which can be helpful for inspecting the dataset.

In [ ]:
train_df["task"].value_counts()

task
H2AFZ                     30000
H3K27ac                   30000
H3K27me3                  30000
H3K36me3                  30000
H3K4me1                   30000
H3K4me2                   30000
H4K20me1                  30000
promoter_all              30000
enhancers_types           30000
enhancers                 30000
splice_sites_acceptors    30000
splice_sites_all          30000
splice_sites_donors       30000
promoter_no_tata          30000
H3K9me3                   27438
H3K9ac                    23274
H3K4me3                   17468
promoter_tata              5062
Name: count, dtype: int64

The Huggingface Dataset has its own `train_test_split` function which can be used to further divide the dataset.

In [ ]:
split_dataset = train_dataset.train_test_split(test_size=0.1)
split_dataset

DatasetDict({
    train: Dataset({
        features: ['sequence', 'name', 'label', 'task'],
        num_rows: 443917
    })
    test: Dataset({
        features: ['sequence', 'name', 'label', 'task'],
        num_rows: 49325
    })
})

This produces another DatasetDict, containing two Datasets - one "train" and one "test".

Other Dataset functions include `select`:

In [ ]:
small_dataset = train_dataset.select(range(50))
print(small_dataset)
print(len(small_dataset))

Dataset({
    features: ['sequence', 'name', 'label', 'task'],
    num_rows: 50
})
50

And `filter`:

In [ ]:
filtered_dataset = train_dataset.filter(lambda x: x["task"]=="H2AFZ")
print(filtered_dataset)

Filter:   0%|          | 0/493242 [00:00<?, ? examples/s]

Dataset({
    features: ['sequence', 'name', 'label', 'task'],
    num_rows: 30000
})

In [ ]:
filtered_df = filtered_dataset.to_pandas()
filtered_df["task"].value_counts()

task
H2AFZ    30000
Name: count, dtype: int64

### What is a tokeniser?

* The tokeniser is used to prepare the data for model input.
* It breaks a sequence into smaller chunks or "tokens".

Related Huggingface pages:
* https://huggingface.co/docs/transformers/en/main_classes/tokenizer
* https://huggingface.co/learn/llm-course/chapter2/4

### How does the Nucleotide Transformer v2 tokeniser work?
* This tokeniser splits sequences into 6-mers - chunks of 6 nucleotides - when possible, otherwise tokenising each nucleotide separately.
* This tokenizer has a vocabulary size of 4105. The inputs of the model are then of the form:
```
<CLS> <ACGTGT> <ACGTGC> <ACGGAC> <GACTAG> <TCAGCA>
```
* The tokenised sequences have a maximum length of 1,000.

Related Huggingface page: https://huggingface.co/InstaDeepAI/nucleotide-transformer-v2-50m-multi-species

In [ ]:
MODEL_NAME = "InstaDeepAI/nucleotide-transformer-v2-50m-multi-species"

In [ ]:
tokeniser = AutoTokenizer.from_pretrained(MODEL_NAME, trust_remote_code=True)

config.json: 0.00B [00:00, ?B/s]

esm_config.py: 0.00B [00:00, ?B/s]

A new version of the following files was downloaded from https://huggingface.co/InstaDeepAI/nucleotide-transformer-v2-50m-multi-species:
- esm_config.py
. Make sure to double-check they do not contain any added malicious code. To avoid downloading new versions of the code file, you can pin a revision.

tokenizer_config.json:   0%|          | 0.00/129 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/101 [00:00<?, ?B/s]

In [ ]:
# https://training.galaxyproject.org/training-material/topics/statistics/tutorials/genomic-llm-finetuning/tutorial.html
tokeniser = transformers.AutoTokenizer.from_pretrained(
    MODEL_NAME,
    model_max_length=512,
    padding_side="right",
    use_fast=True,
    trust_remote_code=True,
)

### Example: Tokenise an example sequence for input into Nucleotide Transformer v2

Let's get an example sequence from the dataset

In [ ]:
sequence = dataset["alt_forward_sequence"][0]
print(sequence)
print(len(sequence))

ACTGGGGTAGTGATGTGTCCTTGTTTCTATCGAGTCAACACAAAATGAATGATCTTTCTTTTAGATTGAAGATGGATACGTGACAATCCCAGGGACCGCTGCACTGACTTCATTTCCTTAGACAAGACACAGTGTAGGGCCCGGCCCGTGTTGGCCCCAGGACTCCTTTGGAATATAGCTGTGGACAATGAATCCTGCGAGCGATGGGGGCACATCAGAGAGCATTTTTGACCTGGACTATGCATCCTGGGGGATCGGCTCCACGCTGATGGTCGCTGGCTTTGTCTTCTACTTGGGCGTCTTTGTGGTCTGCCACCAGCTGTCCTCTTCCCTGAATGCCACTTACCGTTCTTTGGTGGCCAGAGAGAAGGTCTTCTGGGACCTGGCGGCCACGCGTGCAGTCTTTGGTGTTCAGAGCACAGCCGCAGGCCTGTGGGCTCTGCTGGGGGACCCTGTGCTGCATGCCGACAAGGCGCGTGGCCAGCAGAACTGGTGCTGGTTTCACATCACGA
512

By passing the sequence into the tokeniser, we get the input ids and attention mask.

In [ ]:
tok = tokeniser(sequence)
print(tok)

{'input_ids': [1, 5, 277, 2618, 42, 130, 1916, 359, 168, 1267, 52, 2001, 766, 73, 1806, 113, 368, 27, 1232, 158, 62, 844, 1477, 675, 225, 683, 3760, 1220, 13, 1186, 136, 690, 4019, 1880, 402, 225, 52, 177, 93, 1628, 92, 44, 1473, 916, 2314, 308, 111, 1617, 33, 288, 326, 118, 188, 41, 62, 532, 1585, 294, 19, 161, 42, 220, 407, 62, 1151, 13, 1622, 2852, 1145, 157, 3776, 50, 259, 47, 787, 74, 19, 229, 118, 30, 369, 86, 163, 1680, 231, 32, 136, 3114, 178, 277, 1235, 180, 2266, 13, 225, 1589, 3776, 496, 28, 343, 366, 197, 93, 2], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]}

In [ ]:
token_ids = tok["input_ids"]
print(token_ids)

[1, 5, 277, 2618, 42, 130, 1916, 359, 168, 1267, 52, 2001, 766, 73, 1806, 113, 368, 27, 1232, 158, 62, 844, 1477, 675, 225, 683, 3760, 1220, 13, 1186, 136, 690, 4019, 1880, 402, 225, 52, 177, 93, 1628, 92, 44, 1473, 916, 2314, 308, 111, 1617, 33, 288, 326, 118, 188, 41, 62, 532, 1585, 294, 19, 161, 42, 220, 407, 62, 1151, 13, 1622, 2852, 1145, 157, 3776, 50, 259, 47, 787, 74, 19, 229, 118, 30, 369, 86, 163, 1680, 231, 32, 136, 3114, 178, 277, 1235, 180, 2266, 13, 225, 1589, 3776, 496, 28, 343, 366, 197, 93, 2]

In [ ]:
attention_mask = tok["attention_mask"]
print(attention_mask)

[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]

By using the `tokenize` function, we get the tokens themselves.

In [ ]:
tokens = tokeniser.tokenize(sequence)
print(tokens)

['A', 'CTGGG', 'GTAGTGA', 'TGTG', 'TCCTT', 'GTTTCTA', 'TCGA', 'GTCAA', 'CACAAAA', 'TGAA', 'TGATCTT', 'TCTTTTA', 'GATT', 'GAAGATG', 'GATA', 'CGTGA', 'CAA', 'TCCCAGG', 'GACC', 'GCTG', 'CACTGA', 'CTTCATT', 'TCCTTA', 'GACAA', 'GACACA', 'GTGTAGG', 'GCCCGG', 'CC', 'CGTGTT', 'GGCC', 'CCAGGA', 'CTCCTTTG', 'GAATATA', 'GCTGTG', 'GACAA', 'TGAA', 'TCCTG', 'CGA', 'GCGATG', 'GGGG', 'CACA', 'TCAGAGA', 'GCATTTT', 'TGACCTG', 'GACTA', 'TGCA', 'TCCTGGG', 'GGA', 'TCGG', 'CTCCA', 'CGC', 'TGATG', 'GTC', 'GCTG', 'GCTTTG', 'TCTTCTA', 'CTTGG', 'GC', 'GTCTT', 'TGTG', 'GTCTG', 'CCACCA', 'GCTG', 'TCCTCTT', 'CC', 'CTGAATG', 'CCACTTA', 'CCGTT', 'CTTTG', 'GTGGCCA', 'GAGA', 'GAAGG', 'TCTT', 'CTGGGA', 'CCTG', 'GC', 'GGCCA', 'CGC', 'GTG', 'CAGTC', 'TTTG', 'GTGTT', 'CAGAGCA', 'CAGCC', 'GCA', 'GGCC', 'TGTGGG', 'CTCTG', 'CTGGG', 'GGACC', 'CTGTG', 'CTGCATG', 'CC', 'GACAA', 'GGCGC', 'GTGGCCA', 'GCAGAA', 'CTG', 'GTGCTG', 'GTTTCA', 'CATCA', 'CGA']

To decode the sequence, we can put the input ids into the `decode` function.

In [ ]:
decoded = tokeniser.decode(token_ids)
print(decoded)

[CLS] A CTGGG GTAGTGA TGTG TCCTT GTTTCTA TCGA GTCAA CACAAAA TGAA TGATCTT TCTTTTA GATT GAAGATG GATA CGTGA CAA TCCCAGG GACC GCTG CACTGA CTTCATT TCCTTA GACAA GACACA GTGTAGG GCCCGG CC CGTGTT GGCC CCAGGA CTCCTTTG GAATATA GCTGTG GACAA TGAA TCCTG CGA GCGATG GGGG CACA TCAGAGA GCATTTT TGACCTG GACTA TGCA TCCTGGG GGA TCGG CTCCA CGC TGATG GTC GCTG GCTTTG TCTTCTA CTTGG GC GTCTT TGTG GTCTG CCACCA GCTG TCCTCTT CC CTGAATG CCACTTA CCGTT CTTTG GTGGCCA GAGA GAAGG TCTT CTGGGA CCTG GC GGCCA CGC GTG CAGTC TTTG GTGTT CAGAGCA CAGCC GCA GGCC TGTGGG CTCTG CTGGG GGACC CTGTG CTGCATG CC GACAA GGCGC GTGGCCA GCAGAA CTG GTGCTG GTTTCA CATCA CGA [SEP]

### Try it yourself: Tokenise an example sequence for DNABERT-2
Huggingface page: https://huggingface.co/zhihan1996/DNABERT-2-117M

In [ ]:
# Get the model name
MODEL_NAME =

In [ ]:
# Load the tokeniser
# Use a maximum length of 512bp
# Pad on the left side only

In [ ]:
# Get the tokenised output

In [ ]:
# Get the input_ids

In [ ]:
# Decode the input_ids

#### Answer

In [ ]:
MODEL_NAME = "zhihan1996/DNABERT-2-117M"

In [ ]:
# Load the tokeniser
# Use a maximum length of 512bp
# Pad on the left side only
tokeniser = transformers.AutoTokenizer.from_pretrained(
    MODEL_NAME,
    model_max_length=512,
    padding_side="left",
    use_fast=True,
    trust_remote_code=True,
)

In [ ]:
# Get the tokenised output
tokens = tokeniser.tokenize(sequence)
print(tokens)

['A', 'CTGGG', 'GTAGTGA', 'TGTG', 'TCCTT', 'GTTTCTA', 'TCGA', 'GTCAA', 'CACAAAA', 'TGAA', 'TGATCTT', 'TCTTTTA', 'GATT', 'GAAGATG', 'GATA', 'CGTGA', 'CAA', 'TCCCAGG', 'GACC', 'GCTG', 'CACTGA', 'CTTCATT', 'TCCTTA', 'GACAA', 'GACACA', 'GTGTAGG', 'GCCCGG', 'CC', 'CGTGTT', 'GGCC', 'CCAGGA', 'CTCCTTTG', 'GAATATA', 'GCTGTG', 'GACAA', 'TGAA', 'TCCTG', 'CGA', 'GCGATG', 'GGGG', 'CACA', 'TCAGAGA', 'GCATTTT', 'TGACCTG', 'GACTA', 'TGCA', 'TCCTGGG', 'GGA', 'TCGG', 'CTCCA', 'CGC', 'TGATG', 'GTC', 'GCTG', 'GCTTTG', 'TCTTCTA', 'CTTGG', 'GC', 'GTCTT', 'TGTG', 'GTCTG', 'CCACCA', 'GCTG', 'TCCTCTT', 'CC', 'CTGAATG', 'CCACTTA', 'CCGTT', 'CTTTG', 'GTGGCCA', 'GAGA', 'GAAGG', 'TCTT', 'CTGGGA', 'CCTG', 'GC', 'GGCCA', 'CGC', 'GTG', 'CAGTC', 'TTTG', 'GTGTT', 'CAGAGCA', 'CAGCC', 'GCA', 'GGCC', 'TGTGGG', 'CTCTG', 'CTGGG', 'GGACC', 'CTGTG', 'CTGCATG', 'CC', 'GACAA', 'GGCGC', 'GTGGCCA', 'GCAGAA', 'CTG', 'GTGCTG', 'GTTTCA', 'CATCA', 'CGA']

In [ ]:
# Get the input_ids
input_ids = tokeniser(sequence)["input_ids"]
print(input_ids)

[1, 5, 277, 2618, 42, 130, 1916, 359, 168, 1267, 52, 2001, 766, 73, 1806, 113, 368, 27, 1232, 158, 62, 844, 1477, 675, 225, 683, 3760, 1220, 13, 1186, 136, 690, 4019, 1880, 402, 225, 52, 177, 93, 1628, 92, 44, 1473, 916, 2314, 308, 111, 1617, 33, 288, 326, 118, 188, 41, 62, 532, 1585, 294, 19, 161, 42, 220, 407, 62, 1151, 13, 1622, 2852, 1145, 157, 3776, 50, 259, 47, 787, 74, 19, 229, 118, 30, 369, 86, 163, 1680, 231, 32, 136, 3114, 178, 277, 1235, 180, 2266, 13, 225, 1589, 3776, 496, 28, 343, 366, 197, 93, 2]

In [ ]:
# Decode the input_ids
decoded = tokeniser.decode(input_ids)
print(decoded)

[CLS] A CTGGG GTAGTGA TGTG TCCTT GTTTCTA TCGA GTCAA CACAAAA TGAA TGATCTT TCTTTTA GATT GAAGATG GATA CGTGA CAA TCCCAGG GACC GCTG CACTGA CTTCATT TCCTTA GACAA GACACA GTGTAGG GCCCGG CC CGTGTT GGCC CCAGGA CTCCTTTG GAATATA GCTGTG GACAA TGAA TCCTG CGA GCGATG GGGG CACA TCAGAGA GCATTTT TGACCTG GACTA TGCA TCCTGGG GGA TCGG CTCCA CGC TGATG GTC GCTG GCTTTG TCTTCTA CTTGG GC GTCTT TGTG GTCTG CCACCA GCTG TCCTCTT CC CTGAATG CCACTTA CCGTT CTTTG GTGGCCA GAGA GAAGG TCTT CTGGGA CCTG GC GGCCA CGC GTG CAGTC TTTG GTGTT CAGAGCA CAGCC GCA GGCC TGTGGG CTCTG CTGGG GGACC CTGTG CTGCATG CC GACAA GGCGC GTGGCCA GCAGAA CTG GTGCTG GTTTCA CATCA CGA [SEP]

### Example: Tokenise a list of sequences for Nucleotide Transformer v2
Huggingface page: https://huggingface.co/InstaDeepAI/nucleotide-transformer-v2-50m-multi-species

In [ ]:
MODEL_NAME = "InstaDeepAI/nucleotide-transformer-v2-50m-multi-species"

tokeniser = transformers.AutoTokenizer.from_pretrained(
    MODEL_NAME,
    model_max_length=512,
    padding_side="right",
    use_fast=True,
    trust_remote_code=True,
)

Let's select the first five sequences in the dataset as our batch.

In [ ]:
batch = dataset["alt_forward_sequence"][0:5]
print(batch)

['ACTGGGGTAGTGATGTGTCCTTGTTTCTATCGAGTCAACACAAAATGAATGATCTTTCTTTTAGATTGAAGATGGATACGTGACAATCCCAGGGACCGCTGCACTGACTTCATTTCCTTAGACAAGACACAGTGTAGGGCCCGGCCCGTGTTGGCCCCAGGACTCCTTTGGAATATAGCTGTGGACAATGAATCCTGCGAGCGATGGGGGCACATCAGAGAGCATTTTTGACCTGGACTATGCATCCTGGGGGATCGGCTCCACGCTGATGGTCGCTGGCTTTGTCTTCTACTTGGGCGTCTTTGTGGTCTGCCACCAGCTGTCCTCTTCCCTGAATGCCACTTACCGTTCTTTGGTGGCCAGAGAGAAGGTCTTCTGGGACCTGGCGGCCACGCGTGCAGTCTTTGGTGTTCAGAGCACAGCCGCAGGCCTGTGGGCTCTGCTGGGGGACCCTGTGCTGCATGCCGACAAGGCGCGTGGCCAGCAGAACTGGTGCTGGTTTCACATCACGA', 'CCTTGTTTCTATCGAGTCAACACAAAATGAATGATCTTTCTTTTAGATTGAAGATGGATACGTGACAATCCCAGGGACCGCTGCACTGACTTCATTTCCTTAGACAAGACACAGTGTAGGGCCCGGCCCGTGTTGGCCCCAGGACTCCTTTGGAATATAGCTGTGGACAATGAATCCTGCGAGCGATGGGGGCACATCAGAGAGCATTTTTGACCTGGACTATGCATCCTGGGGGATCCGCTCCACGCTGATGGTCCCTGGCTTTGTCTTCTACTTGGGCGTCTTTGTGGTCTGCCACCAGCTGTCCTCTTCCCTGAATGCCACTTACCGTTCTTTGGTGGCCAGAGAGAAGGTCTTCTGGGACCTGGCGGCCACGCGTGCAGTCTTTGGTGTTCAGAGCACAGCCGCAGGCCTGTGGGCTCTGCTGGGGGACCCTGTGCTGCATGCCGACAAGGCGCGTGGCCAGCAGAACTGGTGCTGGTTTCACATCACGACAGCAACGGGATTCTTTT', 'TCTCCATGCAGGCGGGCTGGTCCGAGTCTCTGTTTTGGAAGCTCAACCAGTGGCTGATGATTCACATGTTTCACTGCCGCATGGTTCTAACCTACCACATGTGGTGGGTGTGTTTCTGGCACTGGGACGGCCTGGTCAGCAGCCTGTATCTGCCTCATTTGACACTGTTCCTTGTCGGACTGGCTCTGCTTACGCTAATCATTAATCCATATTGGACCCATAAGAAGACTCAGCAGCTTCTCAATCCGGTGGACTGCAACTTCGCACAGCCAGAAGCCAAGAGCAGGCCAGAAGGCAACGGGCAGCTGCTGCGGAAGAAGAGGCCATAGCTGCTCCAGCCGGGGCTCCGGGGCGGCAGCAGAGCTGGCACACCGATTCTGGGAAGCCCCGCGAATGATGGCTTTTGAATTAATGAGGCAGTGAATGTTTTGTGTTTACTTCTAAGGGAAATACTAACTTTCTTTCGCATTAGTATTAATTTTGAAGTAGCTACAAAGTATTTTTAAGAAATT', 'GGGAACATGTTTCACCATGTCCAGGAAGGGCTGTATTTTTAAGGTCTGTTTTTTCCTTTTTTCCAACAAACAAAACCAAAACAAAACCTAGCCCAGAACTGCACGTGACACATGCGCTCACAAGAACCAGACTACTTGACAGTATTCTTTTAAAACAGGCAAATGAAAGTCGCAGGTGGGTTCTGCCGCCGTCCCGTTCTCACATCTCCCTCTCCGTCGCAGATGCAGAAGCTCGTGAAGGCCGCGAAGGACGGCATCAAGGACGGGCTGGAGAGGACCAGGGCAGCCGTGAAGAGGGGCCGCTCCTTCATCAGGACCAAGTCTCTCATCGCACAGGGTCCGTGCCTGCAGGTCTTCTTGCGGGGAGGACACGGGGTTGGGGGGGGCGGCCACATCTTGTGGGGAGGACTCGGGGTGGGGGGCGGCCGCGCAGGCTCCCACAGCCTTAGGGAGCACCAGCCTGCTCAGTGCTTGGGTCTGAATCAGCCCTGCTGACCCCAGCCTCCCCGTCC', 'TAACACTTCAGAGGGTTTTTAGAGGGAGTAGATGTGAACTTGTGTGTATGATTCACCGTTGTAACTGGAACAGATATGTTTTAAGCAGCGTTATGCATTCCTTTGAGTGTTTCTCTGTCAGATGTTGAGAAACAGAATTGCTGGGGTAGAGGTTTTTTGATCAGTTGTAGTTAAGTTGTGAATGAACAGTAATGTACATTTTGTTTTCTGCATTTTGTCTACAGGTTTCAAAAACTTTTAACAAACAAGTAACTCAGGTTATCTTCAAAGATGGCTACCAGAGCACTTGGGACAAAGCTCAGAAGAGAGGCGTAAAGCTCGTTTCGGTGCTCTGGGTGGAAAAGTAAGCAGTTTCTCTCTTACTTTTTTTCCTTAAGTATCTAGTATTGAAAATGTGTGGAGATATTTTTCACAGATCGCAGAACCAGATAAAGTTTGATTTTCATCTTTTCTCTGCCTCTTACCTCACCTAGTAATTTGAAATCCTCCAGCCTCAATTTCTGTGGTTCAAA']

The tokeniser and its `decode` function can natively handle batches.

In [ ]:
encoded_batch = tokeniser(batch)
print(encoded_batch)

{'input_ids': [[3, 645, 3389, 483, 2659, 1431, 2876, 142, 34, 460, 1387, 1335, 1810, 1994, 2936, 112, 1016, 2980, 632, 1419, 1690, 3209, 553, 1877, 3765, 2749, 1536, 2626, 2475, 1991, 319, 3576, 118, 1700, 3314, 2053, 2188, 825, 2139, 1839, 3882, 1932, 2565, 3189, 2472, 3703, 3956, 2027, 1899, 2347, 4083, 2403, 3949, 2606, 3708, 2460, 2678, 1960, 1329, 1435, 3972, 2258, 3139, 2413, 3887, 4036, 2241, 1939, 2405, 1886, 3304, 948, 1007, 3588, 1663, 4098, 2723, 3710, 1970, 2116, 3813, 2622, 3117, 3565, 3422, 2152, 4105, 4102], [3, 2659, 1431, 2876, 142, 34, 460, 1387, 1335, 1810, 1994, 2936, 112, 1016, 2980, 632, 1419, 1690, 3209, 553, 1877, 3765, 2749, 1536, 2626, 2475, 1991, 319, 3576, 118, 1700, 3314, 2053, 2188, 825, 2139, 1839, 3882, 1932, 2565, 3185, 2472, 3703, 3952, 2027, 1899, 2347, 4083, 2403, 3949, 2606, 3708, 2460, 2678, 1960, 1329, 1435, 3972, 2258, 3139, 2413, 3887, 4036, 2241, 1939, 2405, 1886, 3304, 948, 1007, 3588, 1663, 4098, 2723, 3710, 1970, 2116, 3813, 2622, 3117, 3565, 3422, 2152, 3220, 197, 363, 4103, 4103], [3, 1646, 1941, 3071, 3953, 876, 1883, 3860, 1552, 900, 1826, 1422, 1884, 640, 3621, 1430, 2640, 547, 3973, 1915, 1668, 645, 768, 2014, 3648, 1868, 1964, 354, 2211, 1693, 1784, 2028, 1946, 2966, 1562, 423, 386, 2698, 786, 2452, 924, 1548, 3045, 638, 609, 2196, 2249, 2578, 3652, 2249, 3601, 3988, 1956, 3858, 836, 2132, 1952, 949, 4000, 4097, 3646, 3309, 3624, 2844, 2038, 3761, 2829, 511, 1398, 1293, 1001, 1805, 1379, 3416, 1430, 4038, 1174, 2399, 1470, 1338, 1291, 1481, 1258, 2067, 347, 198, 4103, 4103], [3, 4040, 475, 2215, 3497, 3141, 2519, 1366, 3949, 1371, 2651, 1446, 2062, 46, 38, 170, 3753, 164, 738, 2189, 2974, 2102, 2616, 1181, 570, 1435, 1032, 998, 454, 3518, 3973, 1444, 2995, 2747, 2446, 1648, 1649, 1769, 489, 236, 3529, 3777, 248, 3980, 248, 4077, 3285, 661, 3648, 3529, 1028, 2976, 1420, 976, 223, 2444, 3625, 3953, 1965, 2300, 1437, 3074, 3880, 4091, 4101, 4036, 2188, 1509, 3906, 2501, 3589, 4036, 3006, 4000, 2196, 2389, 3304, 2287, 3689, 1949, 3949, 105, 2724, 1840, 2287, 2739, 4104, 4104], [3, 1064, 1426, 4059, 1337, 3898, 3197, 157, 1914, 1820, 699, 3343, 3854, 3149, 1366, 3649, 1316, 367, 1491, 3423, 2526, 3195, 3270, 2247, 1957, 3922, 3931, 1484, 867, 854, 3453, 118, 2262, 1870, 1379, 1389, 2139, 3480, 987, 2054, 2394, 520, 214, 2453, 1311, 1545, 511, 658, 3627, 4046, 236, 786, 3329, 1044, 1755, 3044, 1669, 1990, 841, 2267, 2463, 1179, 1376, 1299, 409, 1122, 35, 3577, 283, 1422, 3188, 784, 790, 861, 348, 411, 1645, 2667, 670, 2643, 93, 32, 1684, 2439, 1443, 3934, 4102, 4102]], 'attention_mask': [[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]]}

In [ ]:
decoded_batch = tokeniser.decode(encoded_batch["input_ids"])
print(decoded_batch)

['<cls> ACTGGG GTAGTG ATGTGT CCTTGT TTCTAT CGAGTC AACACA AAATGA ATGATC TTTCTT TTAGAT TGAAGA TGGATA CGTGAC AATCCC AGGGAC CGCTGC ACTGAC TTCATT TCCTTA GACAAG ACACAG TGTAGG GCCCGG CCCGTG TTGGCC CCAGGA CTCCTT TGGAAT ATAGCT GTGGAC AATGAA TCCTGC GAGCGA TGGGGG CACATC AGAGAG CATTTT TGACCT GGACTA TGCATC CTGGGG GATCGG CTCCAC GCTGAT GGTCGC TGGCTT TGTCTT CTACTT GGGCGT CTTTGT GGTCTG CCACCA GCTGTC CTCTTC CCTGAA TGCCAC TTACCG TTCTTT GGTGGC CAGAGA GAAGGT CTTCTG GGACCT GGCGGC CACGCG TGCAGT CTTTGG TGTTCA GAGCAC AGCCGC AGGCCT GTGGGC TCTGCT GGGGGA CCCTGT GCTGCA TGCCGA CAAGGC GCGTGG CCAGCA GAACTG GTGCTG GTTTCA CATCAC G A', '<cls> CCTTGT TTCTAT CGAGTC AACACA AAATGA ATGATC TTTCTT TTAGAT TGAAGA TGGATA CGTGAC AATCCC AGGGAC CGCTGC ACTGAC TTCATT TCCTTA GACAAG ACACAG TGTAGG GCCCGG CCCGTG TTGGCC CCAGGA CTCCTT TGGAAT ATAGCT GTGGAC AATGAA TCCTGC GAGCGA TGGGGG CACATC AGAGAG CATTTT TGACCT GGACTA TGCATC CTGGGG GATCCG CTCCAC GCTGAT GGTCCC TGGCTT TGTCTT CTACTT GGGCGT CTTTGT GGTCTG CCACCA GCTGTC CTCTTC CCTGAA TGCCAC TTACCG TTCTTT GGTGGC CAGAGA GAAGGT CTTCTG GGACCT GGCGGC CACGCG TGCAGT CTTTGG TGTTCA GAGCAC AGCCGC AGGCCT GTGGGC TCTGCT GGGGGA CCCTGT GCTGCA TGCCGA CAAGGC GCGTGG CCAGCA GAACTG GTGCTG GTTTCA CATCAC GACAGC AACGGG ATTCTT T T', '<cls> TCTCCA TGCAGG CGGGCT GGTCCG AGTCTC TGTTTT GGAAGC TCAACC AGTGGC TGATGA TTCACA TGTTTC ACTGCC GCATGG TTCTAA CCTACC ACATGT GGTGGG TGTGTT TCTGGC ACTGGG ACGGCC TGGTCA GCAGCC TGTATC TGCCTC ATTTGA CACTGT TCCTTG TCGGAC TGGCTC TGCTTA CGCTAA TCATTA ATCCAT ATTGGA CCCATA AGAAGA CTCAGC AGCTTC TCAATC CGGTGG ACTGCA ACTTCG CACAGC CAGAAG CCAAGA GCAGGC CAGAAG GCAACG GGCAGC TGCTGC GGAAGA AGAGGC CATAGC TGCTCC AGCCGG GGCTCC GGGGCG GCAGCA GAGCTG GCACAC CGATTC TGGGAA GCCCCG CGAATG ATGGCT TTTGAA TTAATG AGGCAG TGAATG TTTTGT GTTTAC TTCTAA GGGAAA TACTAA CTTTCT TTCGCA TTAGTA TTAATT TTGAAG TAGCTA CAAAGT ATTTTT AAGAAA T T', '<cls> GGGAAC ATGTTT CACCAT GTCCAG GAAGGG CTGTAT TTTTAA GGTCTG TTTTTT CCTTTT TTCCAA CAAACA AAACCA AAACAA AACCTA GCCCAG AACTGC ACGTGA CACATG CGCTCA CAAGAA CCAGAC TACTTG ACAGTA TTCTTT TAAAAC AGGCAA ATGAAA GTCGCA GGTGGG TTCTGC CGCCGT CCCGTT CTCACA TCTCCC TCTCCG TCGCAG ATGCAG AAGCTC GTGAAG GCCGCG AAGGAC GGCATC AAGGAC GGGCTG GAGAGG ACCAGG GCAGCC GTGAAG AGGGGC CGCTCC TTCATC AGGACC AAGTCT CTCATC GCACAG GGTCCG TGCCTG CAGGTC TTCTTG CGGGGA GGACAC GGGGTT GGGGGG GGCGGC CACATC TTGTGG GGAGGA CTCGGG GTGGGG GGCGGC CGCGCA GGCTCC CACAGC CTTAGG GAGCAC CAGCCT GCTCAG TGCTTG GGTCTG AATCAG CCCTGC TGACCC CAGCCT CCCCGT C C', '<cls> TAACAC TTCAGA GGGTTT TTAGAG GGAGTA GATGTG AACTTG TGTGTA TGATTC ACCGTT GTAACT GGAACA GATATG TTTTAA GCAGCG TTATGC ATTCCT TTGAGT GTTTCT CTGTCA GATGTT GAGAAA CAGAAT TGCTGG GGTAGA GGTTTT TTGATC AGTTGT AGTTAA GTTGTG AATGAA CAGTAA TGTACA TTTTGT TTTCTG CATTTT GTCTAC AGGTTT CAAAAA CTTTTA ACAAAC AAGTAA CTCAGG TTATCT TCAAAG ATGGCT ACCAGA GCACTT GGGACA AAGCTC AGAAGA GAGGCG TAAAGC TCGTTT CGGTGC TCTGGG TGGAAA AGTAAG CAGTTT CTCTCT TACTTT TTTTCC TTAAGT ATCTAG TATTGA AAATGT GTGGAG ATATTT TTCACA GATCGC AGAACC AGATAA AGTTTG ATTTTC ATCTTT TCTCTG CCTCTT ACCTCA CCTAGT AATTTG AAATCC TCCAGC CTCAAT TTCTGT GGTTCA A A']

The `tokenize` function does not have a native batch mode; instead, it process one string at a time.

In [ ]:
tokens = tokeniser.tokenize(batch)
print(tokens)

TypeError: unhashable type: 'list'

Instead:

In [ ]:
tokens = [tokeniser.tokenize(seq) for seq in batch]
print(tokens)

[['ACTGGG', 'GTAGTG', 'ATGTGT', 'CCTTGT', 'TTCTAT', 'CGAGTC', 'AACACA', 'AAATGA', 'ATGATC', 'TTTCTT', 'TTAGAT', 'TGAAGA', 'TGGATA', 'CGTGAC', 'AATCCC', 'AGGGAC', 'CGCTGC', 'ACTGAC', 'TTCATT', 'TCCTTA', 'GACAAG', 'ACACAG', 'TGTAGG', 'GCCCGG', 'CCCGTG', 'TTGGCC', 'CCAGGA', 'CTCCTT', 'TGGAAT', 'ATAGCT', 'GTGGAC', 'AATGAA', 'TCCTGC', 'GAGCGA', 'TGGGGG', 'CACATC', 'AGAGAG', 'CATTTT', 'TGACCT', 'GGACTA', 'TGCATC', 'CTGGGG', 'GATCGG', 'CTCCAC', 'GCTGAT', 'GGTCGC', 'TGGCTT', 'TGTCTT', 'CTACTT', 'GGGCGT', 'CTTTGT', 'GGTCTG', 'CCACCA', 'GCTGTC', 'CTCTTC', 'CCTGAA', 'TGCCAC', 'TTACCG', 'TTCTTT', 'GGTGGC', 'CAGAGA', 'GAAGGT', 'CTTCTG', 'GGACCT', 'GGCGGC', 'CACGCG', 'TGCAGT', 'CTTTGG', 'TGTTCA', 'GAGCAC', 'AGCCGC', 'AGGCCT', 'GTGGGC', 'TCTGCT', 'GGGGGA', 'CCCTGT', 'GCTGCA', 'TGCCGA', 'CAAGGC', 'GCGTGG', 'CCAGCA', 'GAACTG', 'GTGCTG', 'GTTTCA', 'CATCAC', 'G', 'A'], ['CCTTGT', 'TTCTAT', 'CGAGTC', 'AACACA', 'AAATGA', 'ATGATC', 'TTTCTT', 'TTAGAT', 'TGAAGA', 'TGGATA', 'CGTGAC', 'AATCCC', 'AGGGAC', 'CGCTGC', 'ACTGAC', 'TTCATT', 'TCCTTA', 'GACAAG', 'ACACAG', 'TGTAGG', 'GCCCGG', 'CCCGTG', 'TTGGCC', 'CCAGGA', 'CTCCTT', 'TGGAAT', 'ATAGCT', 'GTGGAC', 'AATGAA', 'TCCTGC', 'GAGCGA', 'TGGGGG', 'CACATC', 'AGAGAG', 'CATTTT', 'TGACCT', 'GGACTA', 'TGCATC', 'CTGGGG', 'GATCCG', 'CTCCAC', 'GCTGAT', 'GGTCCC', 'TGGCTT', 'TGTCTT', 'CTACTT', 'GGGCGT', 'CTTTGT', 'GGTCTG', 'CCACCA', 'GCTGTC', 'CTCTTC', 'CCTGAA', 'TGCCAC', 'TTACCG', 'TTCTTT', 'GGTGGC', 'CAGAGA', 'GAAGGT', 'CTTCTG', 'GGACCT', 'GGCGGC', 'CACGCG', 'TGCAGT', 'CTTTGG', 'TGTTCA', 'GAGCAC', 'AGCCGC', 'AGGCCT', 'GTGGGC', 'TCTGCT', 'GGGGGA', 'CCCTGT', 'GCTGCA', 'TGCCGA', 'CAAGGC', 'GCGTGG', 'CCAGCA', 'GAACTG', 'GTGCTG', 'GTTTCA', 'CATCAC', 'GACAGC', 'AACGGG', 'ATTCTT', 'T', 'T'], ['TCTCCA', 'TGCAGG', 'CGGGCT', 'GGTCCG', 'AGTCTC', 'TGTTTT', 'GGAAGC', 'TCAACC', 'AGTGGC', 'TGATGA', 'TTCACA', 'TGTTTC', 'ACTGCC', 'GCATGG', 'TTCTAA', 'CCTACC', 'ACATGT', 'GGTGGG', 'TGTGTT', 'TCTGGC', 'ACTGGG', 'ACGGCC', 'TGGTCA', 'GCAGCC', 'TGTATC', 'TGCCTC', 'ATTTGA', 'CACTGT', 'TCCTTG', 'TCGGAC', 'TGGCTC', 'TGCTTA', 'CGCTAA', 'TCATTA', 'ATCCAT', 'ATTGGA', 'CCCATA', 'AGAAGA', 'CTCAGC', 'AGCTTC', 'TCAATC', 'CGGTGG', 'ACTGCA', 'ACTTCG', 'CACAGC', 'CAGAAG', 'CCAAGA', 'GCAGGC', 'CAGAAG', 'GCAACG', 'GGCAGC', 'TGCTGC', 'GGAAGA', 'AGAGGC', 'CATAGC', 'TGCTCC', 'AGCCGG', 'GGCTCC', 'GGGGCG', 'GCAGCA', 'GAGCTG', 'GCACAC', 'CGATTC', 'TGGGAA', 'GCCCCG', 'CGAATG', 'ATGGCT', 'TTTGAA', 'TTAATG', 'AGGCAG', 'TGAATG', 'TTTTGT', 'GTTTAC', 'TTCTAA', 'GGGAAA', 'TACTAA', 'CTTTCT', 'TTCGCA', 'TTAGTA', 'TTAATT', 'TTGAAG', 'TAGCTA', 'CAAAGT', 'ATTTTT', 'AAGAAA', 'T', 'T'], ['GGGAAC', 'ATGTTT', 'CACCAT', 'GTCCAG', 'GAAGGG', 'CTGTAT', 'TTTTAA', 'GGTCTG', 'TTTTTT', 'CCTTTT', 'TTCCAA', 'CAAACA', 'AAACCA', 'AAACAA', 'AACCTA', 'GCCCAG', 'AACTGC', 'ACGTGA', 'CACATG', 'CGCTCA', 'CAAGAA', 'CCAGAC', 'TACTTG', 'ACAGTA', 'TTCTTT', 'TAAAAC', 'AGGCAA', 'ATGAAA', 'GTCGCA', 'GGTGGG', 'TTCTGC', 'CGCCGT', 'CCCGTT', 'CTCACA', 'TCTCCC', 'TCTCCG', 'TCGCAG', 'ATGCAG', 'AAGCTC', 'GTGAAG', 'GCCGCG', 'AAGGAC', 'GGCATC', 'AAGGAC', 'GGGCTG', 'GAGAGG', 'ACCAGG', 'GCAGCC', 'GTGAAG', 'AGGGGC', 'CGCTCC', 'TTCATC', 'AGGACC', 'AAGTCT', 'CTCATC', 'GCACAG', 'GGTCCG', 'TGCCTG', 'CAGGTC', 'TTCTTG', 'CGGGGA', 'GGACAC', 'GGGGTT', 'GGGGGG', 'GGCGGC', 'CACATC', 'TTGTGG', 'GGAGGA', 'CTCGGG', 'GTGGGG', 'GGCGGC', 'CGCGCA', 'GGCTCC', 'CACAGC', 'CTTAGG', 'GAGCAC', 'CAGCCT', 'GCTCAG', 'TGCTTG', 'GGTCTG', 'AATCAG', 'CCCTGC', 'TGACCC', 'CAGCCT', 'CCCCGT', 'C', 'C'], ['TAACAC', 'TTCAGA', 'GGGTTT', 'TTAGAG', 'GGAGTA', 'GATGTG', 'AACTTG', 'TGTGTA', 'TGATTC', 'ACCGTT', 'GTAACT', 'GGAACA', 'GATATG', 'TTTTAA', 'GCAGCG', 'TTATGC', 'ATTCCT', 'TTGAGT', 'GTTTCT', 'CTGTCA', 'GATGTT', 'GAGAAA', 'CAGAAT', 'TGCTGG', 'GGTAGA', 'GGTTTT', 'TTGATC', 'AGTTGT', 'AGTTAA', 'GTTGTG', 'AATGAA', 'CAGTAA', 'TGTACA', 'TTTTGT', 'TTTCTG', 'CATTTT', 'GTCTAC', 'AGGTTT', 'CAAAAA', 'CTTTTA', 'ACAAAC', 'AAGTAA', 'CTCAGG', 'TTATCT', 'TCAAAG', 'ATGGCT', 'ACCAGA', 'GCACTT', 'GGGACA', 'AAGCTC', 'AGAAGA', 'GAGGCG', 'TAAAGC', 'TCGTTT', 'CGGTGC', 'TCTGGG', 'TGGAAA', 'AGTAAG', 'CAGTTT', 'CTCTCT', 'TACTTT', 'TTTTCC', 'TTAAGT', 'ATCTAG', 'TATTGA', 'AAATGT', 'GTGGAG', 'ATATTT', 'TTCACA', 'GATCGC', 'AGAACC', 'AGATAA', 'AGTTTG', 'ATTTTC', 'ATCTTT', 'TCTCTG', 'CCTCTT', 'ACCTCA', 'CCTAGT', 'AATTTG', 'AAATCC', 'TCCAGC', 'CTCAAT', 'TTCTGT', 'GGTTCA', 'A', 'A']]

### Example: Tokenise a dataset for Nucleotide Transformer v2
First, let's try to tokenise all the sequences in the `alt_forward_sequence` column.

In [ ]:
alt_seq = dataset["alt_forward_sequence"]
print(alt_seq)

Column(['ACTGGGGTAGTGATGTGTCCTTGTTTCTATCGAGTCAACACAAAATGAATGATCTTTCTTTTAGATTGAAGATGGATACGTGACAATCCCAGGGACCGCTGCACTGACTTCATTTCCTTAGACAAGACACAGTGTAGGGCCCGGCCCGTGTTGGCCCCAGGACTCCTTTGGAATATAGCTGTGGACAATGAATCCTGCGAGCGATGGGGGCACATCAGAGAGCATTTTTGACCTGGACTATGCATCCTGGGGGATCGGCTCCACGCTGATGGTCGCTGGCTTTGTCTTCTACTTGGGCGTCTTTGTGGTCTGCCACCAGCTGTCCTCTTCCCTGAATGCCACTTACCGTTCTTTGGTGGCCAGAGAGAAGGTCTTCTGGGACCTGGCGGCCACGCGTGCAGTCTTTGGTGTTCAGAGCACAGCCGCAGGCCTGTGGGCTCTGCTGGGGGACCCTGTGCTGCATGCCGACAAGGCGCGTGGCCAGCAGAACTGGTGCTGGTTTCACATCACGA', 'CCTTGTTTCTATCGAGTCAACACAAAATGAATGATCTTTCTTTTAGATTGAAGATGGATACGTGACAATCCCAGGGACCGCTGCACTGACTTCATTTCCTTAGACAAGACACAGTGTAGGGCCCGGCCCGTGTTGGCCCCAGGACTCCTTTGGAATATAGCTGTGGACAATGAATCCTGCGAGCGATGGGGGCACATCAGAGAGCATTTTTGACCTGGACTATGCATCCTGGGGGATCCGCTCCACGCTGATGGTCCCTGGCTTTGTCTTCTACTTGGGCGTCTTTGTGGTCTGCCACCAGCTGTCCTCTTCCCTGAATGCCACTTACCGTTCTTTGGTGGCCAGAGAGAAGGTCTTCTGGGACCTGGCGGCCACGCGTGCAGTCTTTGGTGTTCAGAGCACAGCCGCAGGCCTGTGGGCTCTGCTGGGGGACCCTGTGCTGCATGCCGACAAGGCGCGTGGCCAGCAGAACTGGTGCTGGTTTCACATCACGACAGCAACGGGATTCTTTT', 'TCTCCATGCAGGCGGGCTGGTCCGAGTCTCTGTTTTGGAAGCTCAACCAGTGGCTGATGATTCACATGTTTCACTGCCGCATGGTTCTAACCTACCACATGTGGTGGGTGTGTTTCTGGCACTGGGACGGCCTGGTCAGCAGCCTGTATCTGCCTCATTTGACACTGTTCCTTGTCGGACTGGCTCTGCTTACGCTAATCATTAATCCATATTGGACCCATAAGAAGACTCAGCAGCTTCTCAATCCGGTGGACTGCAACTTCGCACAGCCAGAAGCCAAGAGCAGGCCAGAAGGCAACGGGCAGCTGCTGCGGAAGAAGAGGCCATAGCTGCTCCAGCCGGGGCTCCGGGGCGGCAGCAGAGCTGGCACACCGATTCTGGGAAGCCCCGCGAATGATGGCTTTTGAATTAATGAGGCAGTGAATGTTTTGTGTTTACTTCTAAGGGAAATACTAACTTTCTTTCGCATTAGTATTAATTTTGAAGTAGCTACAAAGTATTTTTAAGAAATT', 'GGGAACATGTTTCACCATGTCCAGGAAGGGCTGTATTTTTAAGGTCTGTTTTTTCCTTTTTTCCAACAAACAAAACCAAAACAAAACCTAGCCCAGAACTGCACGTGACACATGCGCTCACAAGAACCAGACTACTTGACAGTATTCTTTTAAAACAGGCAAATGAAAGTCGCAGGTGGGTTCTGCCGCCGTCCCGTTCTCACATCTCCCTCTCCGTCGCAGATGCAGAAGCTCGTGAAGGCCGCGAAGGACGGCATCAAGGACGGGCTGGAGAGGACCAGGGCAGCCGTGAAGAGGGGCCGCTCCTTCATCAGGACCAAGTCTCTCATCGCACAGGGTCCGTGCCTGCAGGTCTTCTTGCGGGGAGGACACGGGGTTGGGGGGGGCGGCCACATCTTGTGGGGAGGACTCGGGGTGGGGGGCGGCCGCGCAGGCTCCCACAGCCTTAGGGAGCACCAGCCTGCTCAGTGCTTGGGTCTGAATCAGCCCTGCTGACCCCAGCCTCCCCGTCC', 'TAACACTTCAGAGGGTTTTTAGAGGGAGTAGATGTGAACTTGTGTGTATGATTCACCGTTGTAACTGGAACAGATATGTTTTAAGCAGCGTTATGCATTCCTTTGAGTGTTTCTCTGTCAGATGTTGAGAAACAGAATTGCTGGGGTAGAGGTTTTTTGATCAGTTGTAGTTAAGTTGTGAATGAACAGTAATGTACATTTTGTTTTCTGCATTTTGTCTACAGGTTTCAAAAACTTTTAACAAACAAGTAACTCAGGTTATCTTCAAAGATGGCTACCAGAGCACTTGGGACAAAGCTCAGAAGAGAGGCGTAAAGCTCGTTTCGGTGCTCTGGGTGGAAAAGTAAGCAGTTTCTCTCTTACTTTTTTTCCTTAAGTATCTAGTATTGAAAATGTGTGGAGATATTTTTCACAGATCGCAGAACCAGATAAAGTTTGATTTTCATCTTTTCTCTGCCTCTTACCTCACCTAGTAATTTGAAATCCTCCAGCCTCAATTTCTGTGGTTCAAA'])

In [ ]:
alt_seq_tok = tokeniser(list(alt_seq)) # The column needs to be converted to a list in order to be passed directly to the tokeniser
print(alt_seq_tok)

{'input_ids': [[3, 645, 3389, 483, 2659, 1431, 2876, 142, 34, 460, 1387, 1335, 1810, 1994, 2936, 112, 1016, 2980, 632, 1419, 1690, 3209, 553, 1877, 3765, 2749, 1536, 2626, 2475, 1991, 319, 3576, 118, 1700, 3314, 2053, 2188, 825, 2139, 1839, 3882, 1932, 2565, 3189, 2472, 3703, 3956, 2027, 1899, 2347, 4083, 2403, 3949, 2606, 3708, 2460, 2678, 1960, 1329, 1435, 3972, 2258, 3139, 2413, 3887, 4036, 2241, 1939, 2405, 1886, 3304, 948, 1007, 3588, 1663, 4098, 2723, 3710, 1970, 2116, 3813, 2622, 3117, 3565, 3422, 2152, 4105, 4102], [3, 2659, 1431, 2876, 142, 34, 460, 1387, 1335, 1810, 1994, 2936, 112, 1016, 2980, 632, 1419, 1690, 3209, 553, 1877, 3765, 2749, 1536, 2626, 2475, 1991, 319, 3576, 118, 1700, 3314, 2053, 2188, 825, 2139, 1839, 3882, 1932, 2565, 3185, 2472, 3703, 3952, 2027, 1899, 2347, 4083, 2403, 3949, 2606, 3708, 2460, 2678, 1960, 1329, 1435, 3972, 2258, 3139, 2413, 3887, 4036, 2241, 1939, 2405, 1886, 3304, 948, 1007, 3588, 1663, 4098, 2723, 3710, 1970, 2116, 3813, 2622, 3117, 3565, 3422, 2152, 3220, 197, 363, 4103, 4103], [3, 1646, 1941, 3071, 3953, 876, 1883, 3860, 1552, 900, 1826, 1422, 1884, 640, 3621, 1430, 2640, 547, 3973, 1915, 1668, 645, 768, 2014, 3648, 1868, 1964, 354, 2211, 1693, 1784, 2028, 1946, 2966, 1562, 423, 386, 2698, 786, 2452, 924, 1548, 3045, 638, 609, 2196, 2249, 2578, 3652, 2249, 3601, 3988, 1956, 3858, 836, 2132, 1952, 949, 4000, 4097, 3646, 3309, 3624, 2844, 2038, 3761, 2829, 511, 1398, 1293, 1001, 1805, 1379, 3416, 1430, 4038, 1174, 2399, 1470, 1338, 1291, 1481, 1258, 2067, 347, 198, 4103, 4103], [3, 4040, 475, 2215, 3497, 3141, 2519, 1366, 3949, 1371, 2651, 1446, 2062, 46, 38, 170, 3753, 164, 738, 2189, 2974, 2102, 2616, 1181, 570, 1435, 1032, 998, 454, 3518, 3973, 1444, 2995, 2747, 2446, 1648, 1649, 1769, 489, 236, 3529, 3777, 248, 3980, 248, 4077, 3285, 661, 3648, 3529, 1028, 2976, 1420, 976, 223, 2444, 3625, 3953, 1965, 2300, 1437, 3074, 3880, 4091, 4101, 4036, 2188, 1509, 3906, 2501, 3589, 4036, 3006, 4000, 2196, 2389, 3304, 2287, 3689, 1949, 3949, 105, 2724, 1840, 2287, 2739, 4104, 4104], [3, 1064, 1426, 4059, 1337, 3898, 3197, 157, 1914, 1820, 699, 3343, 3854, 3149, 1366, 3649, 1316, 367, 1491, 3423, 2526, 3195, 3270, 2247, 1957, 3922, 3931, 1484, 867, 854, 3453, 118, 2262, 1870, 1379, 1389, 2139, 3480, 987, 2054, 2394, 520, 214, 2453, 1311, 1545, 511, 658, 3627, 4046, 236, 786, 3329, 1044, 1755, 3044, 1669, 1990, 841, 2267, 2463, 1179, 1376, 1299, 409, 1122, 35, 3577, 283, 1422, 3188, 784, 790, 861, 348, 411, 1645, 2667, 670, 2643, 93, 32, 1684, 2439, 1443, 3934, 4102, 4102], [3, 146, 1147, 1300, 955, 487, 1691, 3299, 1439, 3474, 1890, 3086, 3101, 2565, 1237, 1371, 3177, 1497, 1299, 1910, 1806, 3341, 1163, 1499, 1662, 1379, 2345, 3422, 15, 1352, 38, 3343, 2235, 412, 55, 3992, 2260, 613, 3206, 3689, 210, 4026, 236, 3421, 3564, 2045, 3081, 1086, 3423, 2458, 2395, 1451, 215, 2362, 1478, 483, 3895, 347, 2194, 1769, 169, 265, 1399, 1383, 2396, 1664, 1624, 2448, 1238, 1398, 428, 2287, 2075, 2533, 1414, 131, 2175, 266, 2632, 1664, 1285, 3081, 3311, 3651, 2678, 3717, 4103, 4102], [3, 2517, 808, 869, 2431, 3209, 1620, 1674, 1559, 1640, 1286, 2387, 2310, 61, 8, 539, 663, 393, 2365, 1898, 2893, 29, 1998, 1754, 2060, 523, 1875, 2567, 1961, 2652, 2666, 1799, 2144, 1518, 294, 322, 809, 60, 431, 672, 1881, 2141, 1806, 1410, 78, 1404, 3452, 1676, 2403, 3654, 395, 1701, 1535, 3199, 3671, 1408, 4003, 2723, 224, 1353, 3527, 2682, 957, 2066, 6, 551, 2026, 4062, 1483, 1203, 900, 27, 1405, 457, 96, 362, 2249, 2939, 2520, 1754, 504, 1060, 300, 1998, 23, 1406, 4104, 4103], [3, 1386, 2151, 1559, 3647, 1402, 1375, 3625, 2293, 2202, 3312, 1534, 911, 2372, 3322, 3712, 2262, 2341, 2403, 637, 1860, 2050, 799, 1541, 824, 1444, 1645, 3439, 2206, 2313, 2031, 3737, 937, 3899, 841, 4050, 2826, 2664, 2423, 2460, 1874, 341, 3107, 1063, 3383, 3723, 2947, 3552, 1819, 3096, 1428, 572, 1654, 3703, 1500, 1435, 904, 901, 3499, 932, 1366, 10, 3349, 2138, 194, 3431, 3081, 521, 611, 1116, 212, 2078, 1411, 3291, 1112, 1410, 363, 214, 3590, 4003, 655, 1370, 667, 2358, 860, 2398, 4105, 4104], [3, 3641, 3390, 3744, 412, 2285, 2473, 4031, 3327, 489, 3761, 4067, 3960, 833, 2224, 66, 3285, 2241, 2562, 3308, 3495, 3332, 3702, 3947, 68, 3821, 3528, 4009, 3832, 2708, 49, 1996, 2721, 2425, 3139, 3179, 2436, 2035, 3243, 3960, 2885, 3969, 936, 829, 2294, 3628, 765, 3701, 4013, 3979, 2693, 3967, 3431, 3965, 4095, 2560, 3706, 581, 2261, 213, 3945, 830, 3685, 4043, 3979, 1699, 2460, 2783, 1433, 996, 1453, 2704, 2567, 3564, 2208, 589, 3285, 2109, 106, 1410, 1992, 789, 248, 19, 2046, 2040, 4102, 4105], [3, 3984, 1991, 4093, 3631, 4072, 1328, 2843, 2010, 1015, 2220, 2878, 927, 2527, 1655, 2027, 2408, 1712, 4076, 986, 2342, 38, 2166, 3972, 2134, 3263, 3138, 4040, 2172, 1682, 939, 1669, 1860, 2099, 3190, 3999, 3646, 2881, 3715, 2767, 2356, 899, 2214, 3908, 2154, 2147, 2226, 3367, 4009, 997, 1968, 2793, 948, 428, 833, 1013, 3332, 3071, 1257, 3321, 3331, 2797, 3045, 3432, 2304, 1029, 1700, 799, 1022, 2024, 3965, 4046, 4053, 3202, 4053, 4053, 3218, 4053, 3538, 149, 1021, 229, 1442, 2260, 2171, 2452, 4104, 4104], [3, 3333, 3333, 2197, 1264, 2531, 2466, 1966, 2916, 1979, 3707, 2564, 1433, 3285, 858, 1476, 1858, 3598, 2270, 2652, 1184, 422, 3086, 3695, 1710, 3648, 2197, 4003, 3845, 3214, 3557, 3701, 1637, 2946, 4016, 2303, 3499, 2215, 3567, 3440, 1591, 1954, 1015, 3982, 2146, 3815, 3100, 2158, 2802, 2689, 4036, 2087, 2691, 3490, 4011, 3565, 2055, 1954, 1381, 2436, 1735, 2162, 2274, 296, 4014, 837, 1086, 2288, 2320, 533, 3088, 1284, 2380, 1392, 928, 1545, 2799, 1295, 1648, 910, 3757, 1014, 3216, 1861, 2328, 3932, 4103, 4102], [3, 7, 1543, 2039, 1393, 3286, 530, 3737, 943, 1516, 127, 3867, 81, 1098, 1370, 953, 1531, 1376, 2653, 347, 3179, 3000, 864, 1704, 3607, 1139, 1892, 2931, 1388, 1713, 2948, 1693, 676, 3330, 3282, 3880, 2836, 3065, 2494, 4048, 471, 2260, 1536, 504, 3720, 2245, 2800, 2755, 3736, 3329, 4036, 2756, 3740, 488, 4033, 4032, 3808, 1774, 3480, 3568, 561, 3069, 2720, 1725, 2564, 2528, 1196, 2308, 3908, 3844, 1665, 1730, 4032, 1796, 3988, 1731, 4096, 3807, 3969, 4080, 4048, 2281, 3988, 2818, 2004, 2305, 4105, 4105], [3, 1704, 3607, 1139, 1892, 2931, 1388, 1713, 2948, 1693, 676, 3330, 3282, 3880, 2836, 3065, 2494, 4048, 471, 2260, 1536, 512, 3720, 2245, 2800, 2755, 3736, 3329, 4036, 2756, 3740, 488, 4033, 4032, 3808, 1774, 3480, 3568, 561, 3069, 2720, 1725, 2564, 2524, 1196, 2308, 3908, 3844, 1665, 1730, 4032, 1796, 3988, 1731, 4096, 3807, 3969, 4080, 4048, 2281, 3988, 2818, 2004, 2305, 3904, 3266, 3775, 1168, 2801, 2813, 1777, 2972, 1692, 2821, 656, 4064, 2561, 3776, 3776, 3712, 3840, 3062, 3713, 3736, 915, 4036, 4105, 4105], [3, 3069, 2720, 1725, 2564, 2528, 1196, 2308, 3908, 3844, 1665, 1730, 4032, 1796, 3988, 1731, 4096, 3807, 3969, 4080, 4048, 2281, 3988, 2818, 2004, 2305, 3904, 3266, 3775, 1168, 2801, 2813, 1777, 2972, 1692, 2821, 656, 4064, 2561, 3776, 3776, 3712, 3840, 3066, 3713, 3736, 915, 4036, 3905, 3843, 3844, 2561, 4020, 3305, 1221, 3008, 3996, 3844, 1688, 1684, 2712, 2815, 1165, 3768, 3588, 3808, 2048, 3648, 3776, 3744, 3780, 2716, 3220, 2812, 2536, 941, 2756, 3072, 177, 3776, 2856, 2695, 2499, 3289, 3316, 3332, 4103, 4105], [3, 2943, 4079, 3498, 2670, 4085, 1012, 4076, 1980, 3029, 2988, 4085, 2284, 3045, 4020, 3493, 1989, 3765, 3246, 3653, 2288, 4045, 3310, 4037, 946, 3028, 2970, 2224, 3776, 3964, 3777, 2412, 2416, 4088, 2229, 3503, 4036, 2996, 2996, 1972, 4017, 3860, 1988, 2349, 2277, 3061, 964, 4068, 4079, 4037, 2802, 3642, 3073, 2997, 2420, 4076, 2348, 2288, 2352, 3994, 2180, 2867, 4084, 3501, 4020, 948, 2996, 2484, 3056, 2418, 2288, 3951, 3625, 2688, 3057, 4006, 2756, 2993, 560, 2079, 3042, 3394, 3826, 4077, 4084, 3541, 4105, 4104], [3, 1441, 1950, 4086, 2462, 3551, 4043, 1017, 2309, 2505, 1593, 1858, 830, 830, 3762, 3971, 2412, 1390, 966, 4071, 1884, 1921, 2457, 364, 803, 3284, 2046, 1038, 199, 1056, 1661, 1627, 2428, 1888, 2726, 2451, 791, 3426, 2859, 2450, 1001, 829, 1894, 2521, 3991, 3496, 2751, 2553, 3794, 2040, 4062, 2335, 3558, 2989, 3055, 2350, 2103, 3125, 2150, 2816, 3687, 2112, 1601, 2815, 3913, 2237, 2676, 940, 2469, 3631, 4004, 3903, 2496, 1533, 3879, 2669, 3421, 91, 3855, 1861, 1918, 1797, 337, 2045, 832, 2582, 4103, 4102], [3, 1597, 1669, 341, 3305, 4077, 222, 3298, 3858, 3602, 3648, 2883, 3947, 2459, 2581, 69, 2147, 1443, 3820, 1227, 2450, 1913, 933, 3606, 521, 86, 1695, 3551, 1387, 3491, 1712, 2092, 850, 1147, 1842, 2412, 789, 2258, 3555, 2093, 2052, 1148, 2224, 3689, 3329, 805, 3269, 1578, 1661, 2100, 2549, 2666, 2598, 3190, 3047, 2097, 3775, 2150, 3742, 3825, 3715, 232, 3567, 2964, 2476, 2046, 2692, 1986, 3692, 3741, 3586, 2159, 2555, 1479, 1410, 610, 4067, 3617, 4043, 741, 3538, 3758, 1046, 1438, 2091, 1235, 4103, 4102], [3, 892, 2039, 1282, 3653, 3702, 3474, 3541, 212, 212, 945, 997, 1631, 2400, 246, 1022, 1499, 2532, 3690, 3167, 2253, 1849, 2564, 264, 54, 1292, 2467, 3483, 1635, 2524, 2734, 617, 1226, 1885, 719, 1641, 254, 3283, 3550, 637, 4074, 1902, 2740, 1662, 4025, 514, 3068, 588, 1918, 751, 3840, 1616, 530, 1809, 3614, 708, 2974, 1556, 2452, 3780, 2006, 3635, 3745, 2287, 2669, 3984, 2029, 3028, 1652, 2435, 4046, 1695, 3931, 3099, 1992, 1493, 3556, 453, 3160, 3587, 3284, 2698, 267, 2446, 602, 3290, 4105, 4104], [3, 343, 1697, 2277, 2965, 1833, 3283, 1277, 2782, 2300, 823, 2445, 2307, 2905, 4014, 3757, 2672, 3413, 3328, 2284, 2964, 2193, 2883, 3861, 3645, 2192, 1368, 1528, 457, 2141, 1391, 3485, 2272, 3744, 2994, 3588, 2464, 1920, 164, 2256, 656, 657, 2533, 2984, 129, 3332, 3311, 3556, 128, 1988, 2456, 457, 2472, 4090, 2949, 1700, 3751, 3838, 1693, 2655, 3200, 2156, 1596, 2479, 1899, 2415, 1496, 1255, 1563, 1451, 2376, 57, 601, 357, 261, 2398, 591, 1517, 3743, 1724, 2392, 378, 1085, 91, 2779, 1170, 4103, 4105], [3, 1347, 3772, 579, 2258, 1639, 3653, 1754, 4080, 943, 3744, 2905, 3908, 2623, 2793, 2600, 3797, 1993, 3987, 3624, 2394, 2434, 2166, 3611, 3424, 1899, 3644, 2988, 2801, 901, 2668, 2532, 2093, 2616, 2216, 2216, 3709, 3825, 2084, 3909, 2880, 1917, 2084, 2537, 2666, 2166, 3694, 3075, 741, 3501, 2990, 1988, 427, 3740, 1828, 2591, 2451, 2672, 1503, 1632, 1402, 2366, 1419, 1391, 1622, 2066, 3226, 3165, 3141, 3676, 152, 1407, 4012, 1459, 2650, 2147, 275, 3099, 1723, 1321, 468, 1002, 2138, 1146, 3643, 1827, 4105, 4103], [3, 1347, 3772, 579, 2258, 1639, 3653, 1754, 4080, 943, 3744, 2905, 3908, 2623, 2793, 2600, 3797, 1993, 3987, 3624, 2394, 2434, 2166, 3611, 3424, 1899, 3644, 2988, 2801, 901, 2668, 2532, 2093, 2616, 2216, 2216, 3709, 3825, 2084, 3909, 2880, 1917, 2084, 2545, 2666, 2166, 3694, 3075, 741, 3501, 2990, 1988, 427, 3740, 1828, 2591, 2451, 2672, 1503, 1632, 1402, 2366, 1419, 1391, 1622, 2066, 3226, 3165, 3141, 3676, 152, 1407, 4012, 1459, 2650, 2147, 275, 3099, 1723, 1321, 468, 1002, 2138, 1146, 3643, 1827, 4105, 4103], [3, 1347, 3772, 579, 2258, 1639, 3653, 1754, 4080, 943, 3744, 2905, 3908, 2623, 2793, 2600, 3797, 1993, 3987, 3624, 2394, 2434, 2166, 3611, 3424, 1899, 3644, 2988, 2801, 901, 2668, 2532, 2093, 2616, 2216, 2216, 3709, 3825, 2084, 3909, 2880, 1917, 2084, 2541, 2666, 2166, 3694, 3075, 741, 3501, 2990, 1988, 427, 3740, 1828, 2591, 2451, 2672, 1503, 1632, 1402, 2366, 1419, 1391, 1622, 2066, 3226, 3165, 3141, 3676, 152, 1407, 4012, 1459, 2650, 2147, 275, 3099, 1723, 1321, 468, 1002, 2138, 1146, 3643, 1827, 4105, 4103], [3, 1119, 2628, 1619, 58, 3724, 542, 2197, 1953, 275, 1370, 13, 3101, 351, 1441, 2515, 1685, 4013, 1940, 2783, 4080, 2303, 1509, 823, 1946, 3963, 3740, 1769, 2301, 1916, 1382, 1955, 914, 2356, 775, 3846, 2711, 283, 611, 3247, 2627, 2729, 3743, 1939, 3830, 837, 3182, 169, 17, 3136, 2102, 2678, 1036, 1080, 660, 994, 3846, 3181, 1853, 330, 1850, 2153, 3312, 1593, 1962, 780, 287, 1733, 1348, 1006, 3765, 3776, 1029, 2018, 2279, 3022, 1709, 3739, 2296, 973, 212, 2622, 9, 1062, 1518, 1992, 4105, 4103], [3, 1453, 3426, 2219, 2649, 3109, 549, 2322, 494, 3226, 430, 1387, 2702, 3110, 3625, 3597, 1628, 1840, 2621, 2728, 693, 1001, 3270, 863, 1197, 1528, 2555, 1014, 3758, 686, 3104, 2411, 1733, 417, 3332, 1632, 3934, 1429, 3293, 2685, 2528, 993, 2563, 3583, 3041, 1504, 544, 995, 419, 1410, 3320, 4073, 3897, 697, 1685, 3705, 1718, 1648, 1566, 3080, 1440, 3240, 1821, 588, 2980, 432, 1425, 2009, 973, 1760, 929, 4041, 480, 1756, 1682, 1728, 992, 2678, 2553, 1237, 505, 2756, 733, 1753, 492, 1013, 4104, 4103], [3, 456, 541, 3152, 1868, 2058, 2683, 1891, 675, 472, 2166, 2522, 122, 842, 2518, 1479, 3611, 7, 264, 101, 3932, 356, 283, 1336, 583, 3915, 1443, 2523, 2362, 356, 2365, 3869, 4013, 3580, 1436, 1427, 1386, 2398, 283, 2912, 216, 2244, 1135, 1105, 1047, 2391, 584, 455, 3419, 347, 150, 1224, 827, 1597, 3399, 278, 1301, 455, 3337, 1517, 1923, 1371, 28, 854, 3603, 1378, 3631, 3725, 1886, 3609, 1811, 550, 978, 1097, 3621, 1437, 1455, 3220, 473, 1387, 1618, 2126, 1115, 1098, 519, 3323, 4103, 4102], [3, 342, 3530, 2628, 1189, 1313, 1199, 3483, 418, 1374, 1119, 1451, 2042, 1406, 3335, 3348, 1590, 587, 1116, 46, 1271, 1414, 1126, 415, 3619, 403, 283, 1047, 279, 2139, 2553, 34, 2104, 346, 2658, 326, 3530, 1388, 252, 1846, 1888, 2079, 1427, 2510, 1562, 3533, 1308, 847, 1423, 1647, 1355, 1699, 1670, 1935, 1887, 1628, 320, 267, 1663, 3150, 1494, 564, 1695, 90, 2507, 1699, 14, 1085, 907, 2196, 2403, 1162, 2119, 1126, 290, 220, 198, 2721, 3292, 987, 1286, 535, 1157, 859, 502, 1078, 4103, 4102], [3, 1571, 2699, 2067, 332, 1952, 1496, 2137, 1942, 1799, 3099, 3687, 93, 267, 1343, 338, 1306, 3660, 1416, 358, 138, 22, 1958, 2107, 20, 1453, 1560, 1893, 214, 851, 999, 411, 3334, 3535, 3915, 1414, 90, 1375, 795, 3727, 3382, 3310, 969, 780, 1428, 1010, 1254, 1934, 3719, 1421, 2472, 1109, 1035, 3355, 2107, 1852, 1557, 1821, 2153, 1887, 1287, 807, 3451, 195, 3747, 1566, 3738, 906, 365, 1562, 1242, 2532, 1146, 537, 127, 1495, 1098, 276, 266, 1038, 1096, 1241, 31, 1410, 1115, 2530, 4103, 4104], [3, 1030, 1158, 121, 1539, 3585, 3844, 675, 108, 920, 1605, 1950, 3977, 780, 610, 677, 3325, 3323, 3645, 930, 3159, 3727, 3756, 2095, 4070, 1235, 199, 2527, 2054, 6, 59, 388, 2438, 1120, 7, 3467, 590, 3815, 1439, 2475, 731, 1939, 1189, 2570, 2656, 2102, 2113, 1670, 784, 978, 3097, 102, 664, 2086, 3139, 3136, 2055, 1686, 118, 3881, 3884, 934, 1428, 646, 3262, 3479, 2167, 3603, 3714, 1045, 1771, 2614, 692, 2968, 2681, 1663, 4037, 3592, 1874, 3681, 470, 1017, 1223, 2045, 3306, 2724, 4105, 4103], [3, 2075, 1951, 1299, 1078, 182, 518, 30, 3577, 900, 1234, 1175, 3078, 1272, 3415, 26, 2422, 4006, 774, 494, 3118, 1014, 1626, 510, 571, 1628, 1106, 1840, 1926, 3920, 1637, 2557, 3036, 808, 411, 3652, 3437, 2846, 1557, 201, 3875, 1446, 3038, 1055, 3427, 654, 1191, 2352, 1946, 3617, 874, 3150, 66, 3275, 2719, 1279, 548, 2374, 614, 842, 1597, 1151, 1403, 1615, 1627, 3674, 520, 2347, 615, 295, 2573, 367, 1443, 2493, 1054, 2184, 2416, 2255, 3940, 2478, 3862, 853, 2565, 2570, 1637, 1637, 4103, 4104], [3, 1383, 124, 844, 2643, 3675, 1082, 359, 1307, 3658, 40, 572, 1937, 198, 546, 3339, 2599, 3299, 2261, 1424, 1078, 365, 2073, 1452, 66, 1300, 2004, 1486, 75, 1355, 1366, 1145, 1051, 10, 75, 1049, 1044, 182, 555, 1195, 3562, 1376, 783, 3438, 3541, 175, 424, 462, 1628, 1392, 780, 2143, 778, 2690, 823, 3112, 124, 968, 3017, 994, 2199, 3344, 873, 3249, 3129, 3714, 2327, 169, 1602, 658, 835, 1231, 1494, 2620, 4040, 3017, 989, 3227, 3344, 789, 2195, 2624, 1452, 262, 236, 1847, 4103, 4104], [3, 1387, 1705, 110, 1433, 80, 1993, 802, 550, 1897, 3121, 3129, 3534, 2339, 169, 1602, 2754, 836, 1999, 278, 2620, 968, 2249, 986, 3227, 3344, 885, 3121, 3129, 3458, 2403, 169, 254, 2272, 939, 2663, 6, 3693, 796, 2587, 2205, 781, 2456, 1332, 790, 2606, 1354, 2502, 2910, 1427, 3346, 2504, 880, 1846, 56, 62, 713, 1590, 542, 653, 2971, 256, 2529, 2447, 3371, 2259, 4042, 1045, 2644, 1539, 133, 3140, 7, 30, 46, 1033, 3675, 1030, 3430, 907, 1399, 1619, 482, 3145, 1277, 4055, 4104, 4102], [3, 456, 525, 1602, 706, 835, 3215, 470, 2620, 976, 3017, 1005, 3223, 272, 873, 3118, 3129, 3410, 2403, 169, 1794, 706, 835, 1999, 1494, 2614, 3982, 3497, 2656, 1558, 20, 1657, 368, 350, 2425, 127, 2347, 681, 272, 651, 1103, 3089, 1419, 2267, 207, 3113, 1709, 774, 806, 904, 3132, 776, 392, 2177, 2390, 4015, 3519, 2211, 606, 3301, 3146, 256, 1259, 4054, 2050, 998, 22, 390, 650, 68, 1370, 19, 1545, 2139, 1820, 1239, 3538, 1082, 3973, 3358, 2558, 747, 1410, 2294, 630, 4073, 4102, 4105], [3, 3180, 303, 457, 1830, 3130, 2117, 3958, 517, 2407, 368, 1365, 1694, 1119, 1227, 1551, 1358, 1077, 1065, 3218, 1002, 2682, 1050, 1864, 146, 2475, 643, 1479, 2683, 141, 2702, 1262, 3593, 2422, 3741, 206, 3421, 1499, 2405, 32, 28, 635, 67, 1359, 1950, 3405, 681, 3358, 1307, 476, 2218, 1033, 547, 1427, 3211, 1590, 553, 1817, 1058, 1550, 1826, 1861, 2628, 334, 2370, 3674, 1360, 3294, 2610, 1548, 2318, 815, 1318, 1155, 283, 365, 1376, 34, 1031, 1859, 1593, 222, 3912, 1644, 76, 553, 4104, 4103], [3, 846, 1029, 1799, 4095, 1559, 1707, 1276, 2442, 1434, 3164, 155, 1162, 762, 578, 2249, 3664, 1866, 333, 1062, 2255, 2648, 2011, 3104, 1878, 2176, 2186, 3732, 63, 1812, 2422, 3219, 1403, 3423, 1526, 422, 360, 1878, 987, 1245, 2451, 1144, 2627, 391, 343, 3438, 2634, 56, 475, 2274, 2140, 776, 573, 314, 460, 141, 461, 1024, 999, 1167, 980, 1355, 1202, 3472, 716, 111, 137, 667, 522, 2007, 343, 1659, 1446, 458, 29, 988, 822, 3477, 1068, 1638, 1128, 575, 1094, 1250, 3742, 3166, 4102, 4102], [3, 3826, 1653, 2447, 3600, 1728, 1769, 3430, 19, 2468, 2453, 2478, 852, 3063, 1170, 1966, 2606, 1965, 3655, 1367, 3419, 850, 3269, 3422, 2591, 2030, 4005, 1634, 623, 3244, 3532, 2225, 1897, 2672, 9, 2562, 1321, 3810, 656, 495, 3247, 1500, 1359, 1190, 775, 622, 32, 475, 2478, 1867, 802, 2635, 1813, 1230, 3129, 739, 84, 854, 3167, 30, 237, 3207, 1051, 1818, 327, 1307, 1490, 2259, 2491, 2525, 3730, 2553, 1939, 3969, 414, 3688, 1976, 2468, 2478, 3934, 903, 1635, 3742, 3740, 2234, 3461, 4102, 4103], [3, 2299, 1380, 479, 3084, 155, 85, 2264, 851, 2502, 277, 11, 1427, 524, 518, 1368, 2102, 262, 931, 486, 2126, 2247, 1319, 905, 2694, 1385, 220, 1051, 2138, 3127, 1375, 1315, 895, 1572, 1966, 2720, 2452, 3622, 1327, 1373, 1631, 3663, 374, 3374, 506, 71, 1558, 10, 1479, 3082, 415, 2637, 774, 3079, 1405, 1290, 1170, 653, 525, 3894, 27, 3418, 774, 860, 891, 1419, 3554, 3555, 3677, 3731, 4095, 3565, 3125, 2815, 3907, 3931, 2416, 2287, 3884, 1618, 2441, 454, 2108, 649, 3326, 3740, 4105, 4105], [3, 4071, 3202, 3617, 2003, 3717, 2460, 2892, 1484, 1852, 511, 548, 487, 3611, 2505, 2408, 1855, 3351, 2322, 2685, 2221, 1955, 287, 206, 1172, 675, 3706, 1866, 1576, 2439, 3848, 1494, 199, 1291, 603, 1371, 63, 1609, 1807, 1327, 67, 286, 3342, 3842, 304, 1419, 1695, 1542, 4078, 3849, 1518, 853, 2628, 1990, 519, 282, 262, 3611, 138, 270, 262, 74, 1047, 74, 134, 1095, 20, 491, 1799, 2363, 2434, 2122, 347, 1618, 1188, 1127, 73, 1817, 3098, 1371, 62, 1370, 2151, 3387, 262, 796, 4103, 4102], [3, 507, 356, 2573, 1750, 1875, 2700, 2715, 1206, 650, 356, 1151, 3344, 2314, 1326, 368, 2059, 1084, 2669, 220, 1833, 1855, 796, 489, 356, 2579, 2724, 3129, 3455, 3098, 1963, 1034, 72, 958, 1375, 484, 1294, 1355, 3538, 71, 415, 1190, 1372, 428, 2221, 2119, 1376, 613, 2230, 1867, 1127, 363, 2258, 360, 1096, 2393, 2502, 70, 1031, 3672, 1033, 534, 1799, 3708, 203, 667, 2027, 679, 473, 2310, 3283, 3659, 1830, 1354, 1098, 1371, 14, 3615, 2975, 3472, 2303, 3901, 2265, 2215, 2500, 1581, 4104, 4102], [3, 398, 2709, 1135, 3641, 597, 352, 1350, 3899, 2363, 3651, 912, 3103, 697, 3269, 3444, 2288, 3693, 2222, 2224, 1918, 2824, 2194, 2737, 1042, 932, 2622, 2883, 3439, 1872, 2977, 2996, 2192, 1984, 1676, 3008, 2960, 1937, 2732, 1665, 2677, 2441, 2447, 2225, 3060, 3565, 3000, 3982, 3704, 4036, 937, 3320, 1092, 3262, 625, 3765, 2164, 1620, 934, 2984, 1713, 3232, 914, 3974, 3129, 2815, 4081, 4094, 4008, 3760, 1728, 3810, 2753, 677, 3252, 651, 2628, 853, 4040, 3701, 981, 3064, 2041, 3285, 773, 2396, 4102, 4105], [3, 1963, 2692, 1323, 799, 3741, 3141, 568, 2527, 2504, 635, 2522, 1399, 1375, 419, 3719, 4059, 2572, 219, 3419, 1675, 1572, 995, 389, 2509, 1130, 1830, 3578, 3973, 1115, 198, 3683, 3468, 412, 982, 2294, 1869, 827, 4068, 2056, 1509, 2800, 1870, 833, 169, 622, 478, 1509, 1999, 40

However, this is not the most efficient way to do things! When working with large datasets or tokenising multiple columns, it is preferable to use the `.map` function.

This is a built-in function of the Huggingface dataset object, and efficiently handles batches and multiprocessing. This approach avoids loading all sequences into memory at once.

In [ ]:
type(dataset)

datasets.arrow_dataset.Dataset

We first define a tokenise function.

In [ ]:
def tokenise_batch(batch):
    return tokeniser(
        batch["alt_forward_sequence"], # Select only the alt_forward_sequence column
        padding=True,
        truncation=True,
        max_length=512,
    )

We then apply this to the dataset using `.map`.

In [ ]:
tokenised_dataset = dataset.map(tokenise_batch, batched=True, batch_size=64)
print(tokenised_dataset)

Map:   0%|          | 0/1018 [00:00<?, ? examples/s]

Dataset({
    features: ['ref_forward_sequence', 'alt_forward_sequence', 'label', 'chromosome', 'position', 'seq', 'ref', 'alt', 'start', 'stop', 'chrom', 'input_ids', 'attention_mask'],
    num_rows: 1018
})

### Try it yourself: Tokenise all the sequences in the `ref_forward_sequence` column

In [ ]:
# Define the tokenise function

In [ ]:
# Tokenise all the sequences in the column

In [ ]:
# Decode the sequences

#### Answer

In [ ]:
# Define the tokenise function
def tokenise_batch(batch):
    return tokeniser(
        batch["ref_forward_sequence"], # Select only the ref_forward_sequence column
        padding=True,
        truncation=True,
        max_length=512,
    )

In [ ]:
# Tokenise all the sequences in the column
tokenised_dataset = dataset.map(tokenise_batch, batched=True, batch_size=64)
print(tokenised_dataset)

Map:   0%|          | 0/1018 [00:00<?, ? examples/s]

Dataset({
    features: ['ref_forward_sequence', 'alt_forward_sequence', 'label', 'chromosome', 'position', 'seq', 'ref', 'alt', 'start', 'stop', 'chrom', 'input_ids', 'attention_mask'],
    num_rows: 1018
})

In [ ]:
# Decode the sequences

# Method 1: list
decoded = tokeniser.decode(list(tokenised_dataset["input_ids"]))
print(decoded)

['<cls> ACTGGG GTAGTG ATGTGT CCTTGT TTCTAT CGAGTC AACACA AAATGA ATGATC TTTCTT TTAGAT TGAAGA TGGATA CGTGAC AATCCC AGGGAC CGCTGC ACTGAC TTCATT TCCTTA GACAAG ACACAG TGTAGG GCCCGG CCCGTG TTGGCC CCAGGA CTCCTT TGGAAT ATAGCT GTGGAC AATGAA TCCTGC GAGCGA TGGGGG CACATC AGAGAG CATTTT TGACCT GGACTA TGCATC CTGGGG GATCCG CTCCAC GCTGAT GGTCGC TGGCTT TGTCTT CTACTT GGGCGT CTTTGT GGTCTG CCACCA GCTGTC CTCTTC CCTGAA TGCCAC TTACCG TTCTTT GGTGGC CAGAGA GAAGGT CTTCTG GGACCT GGCGGC CACGCG TGCAGT CTTTGG TGTTCA GAGCAC AGCCGC AGGCCT GTGGGC TCTGCT GGGGGA CCCTGT GCTGCA TGCCGA CAAGGC GCGTGG CCAGCA GAACTG GTGCTG GTTTCA CATCAC G A', '<cls> CCTTGT TTCTAT CGAGTC AACACA AAATGA ATGATC TTTCTT TTAGAT TGAAGA TGGATA CGTGAC AATCCC AGGGAC CGCTGC ACTGAC TTCATT TCCTTA GACAAG ACACAG TGTAGG GCCCGG CCCGTG TTGGCC CCAGGA CTCCTT TGGAAT ATAGCT GTGGAC AATGAA TCCTGC GAGCGA TGGGGG CACATC AGAGAG CATTTT TGACCT GGACTA TGCATC CTGGGG GATCCG CTCCAC GCTGAT GGTCGC TGGCTT TGTCTT CTACTT GGGCGT CTTTGT GGTCTG CCACCA GCTGTC CTCTTC CCTGAA TGCCAC TTACCG TTCTTT GGTGGC CAGAGA GAAGGT CTTCTG GGACCT GGCGGC CACGCG TGCAGT CTTTGG TGTTCA GAGCAC AGCCGC AGGCCT GTGGGC TCTGCT GGGGGA CCCTGT GCTGCA TGCCGA CAAGGC GCGTGG CCAGCA GAACTG GTGCTG GTTTCA CATCAC GACAGC AACGGG ATTCTT T T', '<cls> TCTCCA TGCAGG CGGGCT GGTCCG AGTCTC TGTTTT GGAAGC TCAACC AGTGGC TGATGA TTCACA TGTTTC ACTGCC GCATGG TTCTAA CCTACC ACATGT GGTGGG TGTGTT TCTGGC ACTGGG ACGGCC TGGTCA GCAGCC TGTATC TGCCTC ATTTGA CACTGT TCCTTG TCGGAC TGGCTC TGCTTA CGCTAA TCATTA ATCCAT ATTGGA CCCATA AGAAGA CTCAGC AGCTTC TCAATC CGGTGG ACTGGA ACTTCG CACAGC CAGAAG CCAAGA GCAGGC CAGAAG GCAACG GGCAGC TGCTGC GGAAGA AGAGGC CATAGC TGCTCC AGCCGG GGCTCC GGGGCG GCAGCA GAGCTG GCACAC CGATTC TGGGAA GCCCCG CGAATG ATGGCT TTTGAA TTAATG AGGCAG TGAATG TTTTGT GTTTAC TTCTAA GGGAAA TACTAA CTTTCT TTCGCA TTAGTA TTAATT TTGAAG TAGCTA CAAAGT ATTTTT AAGAAA T T', '<cls> GGGAAC ATGTTT CACCAT GTCCAG GAAGGG CTGTAT TTTTAA GGTCTG TTTTTT CCTTTT TTCCAA CAAACA AAACCA AAACAA AACCTA GCCCAG AACTGC ACGTGA CACATG CGCTCA CAAGAA CCAGAC TACTTG ACAGTA TTCTTT TAAAAC AGGCAA ATGAAA GTCGCA GGTGGG TTCTGC CGCCGT CCCGTT CTCACA TCTCCC TCTCCG TCGCAG ATGCAG AAGCTC GTGAAG GCCGCG AAGGAC GGCACC AAGGAC GGGCTG GAGAGG ACCAGG GCAGCC GTGAAG AGGGGC CGCTCC TTCATC AGGACC AAGTCT CTCATC GCACAG GGTCCG TGCCTG CAGGTC TTCTTG CGGGGA GGACAC GGGGTT GGGGGG GGCGGC CACATC TTGTGG GGAGGA CTCGGG GTGGGG GGCGGC CGCGCA GGCTCC CACAGC CTTAGG GAGCAC CAGCCT GCTCAG TGCTTG GGTCTG AATCAG CCCTGC TGACCC CAGCCT CCCCGT C C', '<cls> TAACAC TTCAGA GGGTTT TTAGAG GGAGTA GATGTG AACTTG TGTGTA TGATTC ACCGTT GTAACT GGAACA GATATG TTTTAA GCAGCG TTATGC ATTCCT TTGAGT GTTTCT CTGTCA GATGTT GAGAAA CAGAAT TGCTGG GGTAGA GGTTTT TTGATC AGTTGT AGTTAA GTTGTG AATGAA CAGTAA TGTACA TTTTGT TTTCTG CATTTT GTCTAC AGGTTT CAAAAA CTTTTA ACAAAC AAGTAA CTCACG TTATCT TCAAAG ATGGCT ACCAGA GCACTT GGGACA AAGCTC AGAAGA GAGGCG TAAAGC TCGTTT CGGTGC TCTGGG TGGAAA AGTAAG CAGTTT CTCTCT TACTTT TTTTCC TTAAGT ATCTAG TATTGA AAATGT GTGGAG ATATTT TTCACA GATCGC AGAACC AGATAA AGTTTG ATTTTC ATCTTT TCTCTG CCTCTT ACCTCA CCTAGT AATTTG AAATCC TCCAGC CTCAAT TTCTGT GGTTCA A A', '<cls> AACAGA TATGTT TTAAGC AGCGTT ATGCAT TCCTTT GAGTGT TTCTCT GTCAGA TGTTGA GAAACA GAATTG CTGGGG TAGAGG TTTTTT GATCAG TTGTAG TTAAGT TGTGAA TGAACA GTAATG TACATT TTGTTT TCTGCA TTTTGT CTACAG GTTTCA AAAACT TTTAAC AAACAA GTAACT CACGTT ATCTTC AAAGAT GGCTAC CAGAGC ACTTGG GACAAA GCTCAG AAGAGA GGCGTA AAGCTC GTTTCG GTGCTC TGGGTG GAAAAG TAAGCA GTTTCT CTCTTA CTTTTT TTCCTT AAGTAT CTAGTA TTGAAA ATGTGT GGAGAT ATTTTT CACAGA TCGCAG AACCAG ATAAAG TTTGAT TTTCAT CTTTTC TCTGCC TCTTAC CTCACC TAGTAA TTTGAA ATCCTC CAGCCT CAATTT CTGTGG TTCAAA AATGGT CATGCT ATAATA CCTAAC TCTGCC TAGGGG GAAAAG GAGCCT GCAGGT CCTGAA GCTGGG T A', '<cls> CTGAGG AGACAC AGTTGG CTTGCT GACAAG TCTAGC TCCATA TCATAT TCTCAC TTAAAA CTTAGT CTAAAA AAAGTG AAAAAC ACATTT ACCTAT ATCAAG CTAGTG TGTCTA CGTATG AAATTG TGGACA TCGTTA CAAATC ACAATT TGTAGT CCAAAT TGCCAG CCTTTC CCTCTA TGAAAT CATTCC TTGCCA ATACAA ATAGGA AGACAG AAAGTC ATCCCT ACCTCC TGTTAG CATTTG TGAACA TTTGCA AATACA TTTGTC GTTGTC TCCATC CTTTGT GCTAAA ATCATT TCCTGG TTGGCT GATGCT GCTTAT TTTGCC GGCTGT CCCTGT AAGTCC TTTAAG GTGAAT CCTGTA AGCGTG CAAAGA AAAAAA ACACAT TGGCTA GGGTCA TTGATT TACCGT AGTGGC AAATTT TTTGTG ATGAAG AATTCC ATTCTA CAGAAG CGTGTT CTGTAC TCGTTA ATGGAC TAATGC ATACTC TGGACA AAATAT TTTGCA C T', '<cls> TTTCTA CATCAT TCATAT GCAGCT TTTGTA TTTTCT GCACAG CAGCGG CACTTA GAGCCC TTGGCA AGCACT CTAGGC GAGGTA GCTGCC CAGTAA CTATGG CTTTGT ACTGTG TGAGGC TGGGGA AGATCT TTGGGG AGAGAC TTCTGC TCTCTG GTTCCT CACTCA CTAAAG TGGCCT GCCTAG AGCCAG GGAGTT AGTAAG GGGAGA CGAATA CCTCAC CTTGAT CTCTTC TGTAGA ATTAGG GAATGT TAACGT GTAGAT GCCATT CGTGGT GTGTCC TGATTT GAATAC TTCAGC ACAGTC TCTGAA GCTGAT TTGTTC TTCTTT AGCAAC AGTGGG GTCCTT AGCTGC TTTTAA AAAATA GTAAGG CATTTA AACGGA GTTCAT GAAAAG ACAAAG ACTTGT TATTTC AAGAGC CAATCA TTTGGT GAGTTT TATTAC TTTGGA ATTCTT AAGTAA GCAAAA GGCTGT ACCACT TTTTTA ACCTTT CTAGAA AGTTTC CTTTCA G C', '<cls> GCAGAG GTAGCA GCCTCC ATCTTC CAGCTG CTCCAG GGCGCT GAGGCT ATGCAG GCCCCG GGGTGT GGTGAC AGAGCG CACCCC AAAGGA GAGAGG CACGCG CTGGGA GAGCTC GTCCAT GAGGGC GCTGAA GGTCTT AAAGGC GCGCTG GTGAAC GGCCAG GCGGAC CCCAGC AAACCG TGGATC CCCTCG CTTGAG GAAGGT GATCTT CTTGGC TGGCGT GACCTT GGTGAC CGAGGG GGTGCG AGCCAC AGAGGG CAGGAA GCACTC ACGGTG GCTCGG GGCCTG GGCATT CCTGGG GGTGCT GTTCAT GGTGTG GGGGCT CTGGCC GCTGTA ACAGGG CAGAGG AAGAGG GGTCAG AGAGCA GCTTGG GGGATT GGCATT TCCTGT CTCTTC CCGTCT TTCTAG AGGTGC TTCCTG CCCACC CCAAAT GTGCTC CACTCC ACTATG GAGAGG CAAGTG AATCTA TTTGGA TGGAAC AGAAGG AAGGAC AAAAGT TGGGCA TGGGAC A G', '<cls> GGCACC TGGAAT GGGGTG GCACCT GGGCAC TTACCC CGATTT TGGTTA AGGGAT CACCTC CGAGCA AGCTCT CTGTCT TCTGAT TGGCTT CTTCAC TCCCCC GGGCTC AGGTTA CTACAA AAACAA CATGAA GGTGGC CATTAA GACGCT GAAGGA GGGAAC CATGTC TCCAGA AGCCTT TCTGGG TGAGGC CAACGT GATGAA GGCTCT GCAGCA CGAGCG GCTGGT CCGACT CTACGC AGTGGT CACCAA GGAGCC CATCTA CATTGT CACCGA GTACAT GGCCAG AGGTGG TGCCCC CCGCAG AGCCGC ATCCTC AGAGCG AGGCGG GAGGGC CGGGCT TAGCAG GAGGAG GAGGGT CCGCTG CGGTGG GTTCAC CAGGCC AGGGGG TCCTGC AGATCT AGGGCA TGGCAC GGTGTG GGGACA GGGAGG GATGGA GGGAGG GGGAGG GACAGA GGGAGG GTGAGA AACAGG AGGGTG AAGTGG TTCTGA CAGAGC CATGTT CTCAGC C C', '<cls> GAGGGG GAGGGG CACAGG TAGCCC CTGTGT CTCTGA TGCCCA CGTTGC TGCGTT GCTGTT CTGGGC TTCTAG GAGAGG AGTTTA TTCGGC TGAGGA GCAACA CAGTCA CCTTTC TACTCC ATCCAA GAAACA GCTCCT TCCCCA GCAGCC CACAGG GGCTGT GCGGGG GACACA GTGTGG GCTCGG TCTTGG CGTGGA GGCCCC CAGGCT GTCCTT CACCAT GTGCCT GTTCCC TCAGAT TGCTGA AGGGAT GGCATA CATTGA GCGCAT GAATTC CATCCA CCGCGA CCTGCG GGCGGC CAACAT CCTGGT GTCTGA GGCCTT GTGCTG CAAAAT TGCTGA TTTTGG CTTGGC TCGAAT CATCGA CAGTGA ATACAC GGCCCA AGAGGG TAAGCA CAGCCC CTAACC ACAAGG GAAACC TAGGGC CTTATC TTTCCC AGCTCC TCAAAG CCGCCT TTAACT TCTCCC AGCACA GCCCTG AGGGAA GACACC TGAGGG CTATAC GGTTTC T A', '<cls> AAAAAT TCAAAT TGGGAT TTTCCG GAGTAA ACAAGA GCCTAG AGCCCT TTGCTC AATGCT GGATTT AATACG TATATA TTTTTA AGCGAG TTGGTT TTTTCC CCTTTG ATTTTT GATCTT CGCGAC AGTTCC TCCCAC GCATAT TATCGT TGTTGC CGTCGT TTTCTC TCCCCG CGTGGC TCCTTG ACCTGC GAGGGA GAGAGA GGACAC CGAAGC CGGGAG CTCGCA GGGACC ATGTAT CAGAGC TTGGCC ATGGCC GCCAAC CACGGG CCGCCC CCCGGT GCCTAC GAGGCG GGCGGC CCCGGC GCCTTC ATGCAC GGCGCG GGCGCC GCGTCC TCGCCA GTCTAC GTGCCC ACACCG CGGGTG CCCTCC TCCGTG CTGGGC CTGTCC TACCTC CAGGGC GGAGGC GCGGGC TCTGCG TCCGGA GGCGCC TCGGGC GGCAGC TCCGGT GGGGCC GCGTCT GGTGCG GGGCCC GGGACC CAGCAG GGCAGC CCGGGA TGGAGC CAGGCG G G', '<cls> TCCCAC GCATAT TATCGT TGTTGC CGTCGT TTTCTC TCCCCG CGTGGC TCCTTG ACCTGC GAGGGA GAGAGA GGACAC CGAAGC CGGGAG CTCGCA GGGACC ATGTAT CAGAGC TTGGCC ATGGCC GCCAAC CACGGG CCGCCC CCCGGT GCCTAC GAGGCG GGCGGC CCCGGC GCCTTC ATGCAC GGCGCG GGCGCC GCGTCC TCGCCA GTCTAC GTGCCC ACACCG CGGGTG CCCTCC TCCGTG CTGGGC CTGTCC TACCTC CAGGGC GGAGGC GCGGGC TCTGCG TCCGGA GGCGCC TCGGGC GGCAGC TCCGGT GGGGCC GCGTCT GGTGCG GGGCCC GGGACC CAGCAG GGCAGC CCGGGA TGGAGC CAGGCG GGAGCC GACGGA GCCGCT TACACC CCGCCG CCGGTG TCGCCG CGCTTC TCCTTC CCGGGG ACCACC GGGTCC CTGGCG GCCGCC GCCGCC GCTGCC GCGGCC CGGGAA GCTGCG GCCTAC AGCAGT GGCGGC G G', '<cls> CGGGTG CCCTCC TCCGTG CTGGGC CTGTCC TACCTC CAGGGC GGAGGC GCGGGC TCTGCG TCCGGA GGCGCC TCGGGC GGCAGC TCCGGT GGGGCC GCGTCT GGTGCG GGGCCC GGGACC CAGCAG GGCAGC CCGGGA TGGAGC CAGGCG GGAGCC GACGGA GCCGCT TACACC CCGCCG CCGGTG TCGCCG CGCTTC TCCTTC CCGGGG ACCACC GGGTCC CTGGCG GCCGCC GCCGCC GCTGCC GCGGCC CGGGAA GCTGCG GCCTAC AGCAGT GGCGGC GGAGCG GCGGGT GCGGGC CTGGCG GGCCGC GAGCAG TACGGG CGCGCC GGCTTC GCGGGC TCCTAC TCCAGC CCCTAC CCGGCT TACATG GCCGAC GTGGGC GCGTCC TGGGCC GCAGCC GCCGCC GCCTCC GCCGGC CCCTTC GACAGC CCGGTC CTGCAC AGCCTG CCCGGC CGGGCC AACCCG GCCGCC CGACAC CCCAAT CTCGGT GAGTAG GAGCGC GAGGGC T G', '<cls> CGTGCT GGGCCT GTCCTA CCTCCA GGGCGG AGGCGC GGGCTC TGCGTC CGGAGG CGCCTC GGGCGG CAGCTC CGGTGG GGCCGC GTCTGG TGCGGG GCCCGG GACCCA GCAGGG CAGCCC GGGATG GAGCCA GGCGGG AGCCGA CGGAGC CGCTTA CACCCC GCCGCC GGTGTC GCCGCG CTTCTC CTTCCC GGGGAC CACCGG GTCCCT GGCGGC CGCCGC CGCCGC TGCCGC GGCCCG GGAAGC TGCGGC CTACAG CAGTGG CGGCGG AGCGGC GGGTGC GGGCCT GGCGGG CCGCGA GCAGTA CGGGCG CGCCGG CTTCGC GGGCTC CTACTC CAGCCC CTACCC GGCTTA CATGGC CGACGT GGGCGC GTCCTG GGCCGC AGCCGC CGCCGC CTCCGC CGGCCC CTTCGA CAGCCC GGTCCT GCACAG CCTGCC CGGCCG GGCCAA CCCGGC CGCCCG ACACCC CAATCT CGGTGA GTAGGA GCGCGA GGGCTG GGGCGC GTGAGG G C', '<cls> TTCTCG TGCTCA GGGGAA CTCTCA GTGTCT GGGATT AGGGAG CAGGGG CTGAAG TCAGAG TGAGGA AGAGCA AGAGCA GCCCGA GGTGGT CTTCTC TTTCCA AGGAAA GGGCAT TGTTTC TGTGCG CTCTAG ATTCTC AGATGT GAGAGC TGGGCA TAAACA AAGAAT TAATCC TCTGTG TCTTTT CTTGTC TGTTCC CCCCAA CTCAGT AGATAT GTTTGA CGACTT CTCAGA AGGCAG AGAGTG TGTCAA CTGTGG GGCTAT GTCCAC CCCGCT CTGGAG GCGAGA TGGGAC GGGTCA CTATCT GTGCAA CGCCTG CGGCCT CTACCA CAAGAT GAACGG CATCAA CCGGCC GCTCAT CAAGCC TCAGCG CCGGCT GGTAAG CACGTG CCTCGC AGCCTC CTCTGG GCACCT GGCTGC GGAGCT CTCGCC TTGGTG GGACAT CCTCTG GTTTTG AATTTT GGAACT TGAGGG TGTGCA TCGGGG ATTACG TGGGTG AGAGCC CCATAA T A', '<cls> TCAGTG TCTGGG ATTAGG GAGCAG GGGCTG AAGTCA GAGTGA GGAAGA GCAAGA GCAGCC CGAGGT GGTCTT CTCTTT CCAAGG AAAGGG CATTGT TTCTGT GCGCTC TAGATT CTCAGA TGTGAG AGCTGG GCATAA ACAAAG AATTAA TCCTCT GTGTCT TTTCTT GTCTGT TCCCCC CAACTC AGTAGA TATGTT TGACGA CTTCTC AGAAGG CAGAGA GTGTGT CAACTG TGGGGC TATGTC CACCCC GCTCTG GAGGCG AGATGG GACGGG TCACTA TCTGTG CAACGC CTGCGG CCTCTA CCACAA GATGAA CGGCAT CAACCG GCCGCT CATCAA GCCTCA GCGCCG GCTGGT AAGCAC GTGCCT CGCAGC CTCCTC TGGGCA CCTGGC TGCGGA GCTCTC GCCTTG GTGGGA CATCCT CTGGTT TTGAAT TTTGGA ACTTGA GGGTGT GCATCG GGGATT ACGTGG GTGAGA GCCCCA TAATAA TTCTCA CAACTT TAGAGT T A', '<cls> AGTGTC TGGGAT TAGGGA GCAGGG GCTGAA GTCAGA GTGAGG AAGAGC AAGAGC AGCCCG AGGTGG TCTTCT CTTTCC AAGGAA AGGGCA TTGTTT CTGTGC GCTCTA GATTCT CAGATG TGAGAG CTGGGC ATAAAC AAAGAA TTAATC CTCTGT GTCTTT TCTTGT CTGTTC CCCCCA ACTCAG TAGATA TGTTTG ACGACT TCTCAG AAGGCA GAGAGT GTGTCA ACTGTG GGGCTA TGTCCA CCCCGC TCTGGA GGCGAG ATGGGA CGGGTC ACTATC TGTGCA ACGCCT GCGGCC TCTACC ACAAGA TGAACG GCATCA ACCGGC CGCTCA TCAAGC CTCAGC GCCGGC TGGTAA GCACGT GCCTCG CAGCCT CCTCTG GGCACC TGGCTG CGGAGC TCTCGC CTTGGT GGGACA TCCTCT GGTTTT GAATTT TGGAAC TTGAGG GTGTGC ATCGGG GATTAC GTGGGT GAGAGC CCCATA ATAATT CTCACA ACTTTA GAGTTA G C', '<cls> ATTTAT TCCTCG CAGTGG CGCAGG TGACAG GAGAGT TAGGTG CCGTCA CAGGTC AGAGAT CTCATG CAGGGT CGTTAG GGCCCA GCCCTG CCTCCC GTTAGG GAGGCC CAGCTC CGCAGC CACACG CGAGGT GGAAGG GCAGTG CACACC TTTTAC TTGGAC ATGAAG CATTTG TTTCCT GTCTTG CAGTCC GCCTCC CGCCGA GTGGGC CTCTCC TGTGCC AACTGC CAGACC ACCACC ACCACG CTGTGG CGCCGC AATGCG GAGGGC GAGCCT GTGTGC AATGCC TGCGGC CTCTAC ATGAAG CTCCAC GGGGTA CGTGGG TCCTGC GCCCAT GCGGCA TCCTTG CCTTCT GATGCC CATCTC TCAGTC CTCCCT TGTCTT CTTCCT TTGTAC TAGCAT TCATTT TTCCTT CTTAAC AAAGAG ACTTAG ATTTGG AAGGGG CTTTCA ACTACT TTGCTG GCCTCT TCCGTC CTTTAC ATTGTA TAAGTG AATTTT CCGTTT TACAGA T G', '<cls> TTAGGT GCCGTC ACAGGT CAGAGA TCTCAT GCAGGG TCGTTA GGGCCC AGCCCT GCCTCC CGTTAG GGAGGC CCAGCT CCGCAG CCACAC GCGAGG TGGAAG GGCAGT GCACAC CTTTTA CTTGGA CATGAA GCATTT GTTTCC TGTCTT GCAGTC CGCCTC CCGCCG AGTGGG CCTCTC CTGTGC CAACTG CCAGAC CACCAC CACCAC GCTGTG GCGCCG CAATGC GGAGGG CGAGCC TGTGTG CAATGC CTGCGG CCTCTA CATGAA GCTCCA CGGGGT ACGTGG GTCCTG CGCCCA TGCGGC ATCCTT GCCTTC TGATGC CCATCT CTCAGT CCTCCC TTGTCT TCTTCC TTTGTA CTAGCA TTCATT TTTCCT TCTTAA CAAAGA GACTTA GATTTG GAAGGG GCTTTC AACTAC TTTGCT GGCCTC TTCCGT CCTTTA CATTGT ATAAGT GAATTT TCCGTT TTACAG ATGAGC AGGCTA CATTTA TATGTA GCAGTT TGATGT G T', '<cls> TTAGGT GCCGTC ACAGGT CAGAGA TCTCAT GCAGGG TCGTTA GGGCCC AGCCCT GCCTCC CGTTAG GGAGGC CCAGCT CCGCAG CCACAC GCGAGG TGGAAG GGCAGT GCACAC CTTTTA CTTGGA CATGAA GCATTT GTTTCC TGTCTT GCAGTC CGCCTC CCGCCG AGTGGG CCTCTC CTGTGC CAACTG CCAGAC CACCAC CACCAC GCTGTG GCGCCG CAATGC GGAGGG CGAGCC TGTGTG CAATGC CTGCGG CCTCTA CATGAA GCTCCA CGGGGT ACGTGG GTCCTG CGCCCA TGCGGC ATCCTT GCCTTC TGATGC CCATCT CTCAGT CCTCCC TTGTCT TCTTCC TTTGTA CTAGCA TTCATT TTTCCT TCTTAA CAAAGA GACTTA GATTTG GAAGGG GCTTTC AACTAC TTTGCT GGCCTC TTCCGT CCTTTA CATTGT ATAAGT GAATTT TCCGTT TTACAG ATGAGC AGGCTA CATTTA TATGTA GCAGTT TGATGT G T', '<cls> TTAGGT GCCGTC ACAGGT CAGAGA TCTCAT GCAGGG TCGTTA GGGCCC AGCCCT GCCTCC CGTTAG GGAGGC CCAGCT CCGCAG CCACAC GCGAGG TGGAAG GGCAGT GCACAC CTTTTA CTTGGA CATGAA GCATTT GTTTCC TGTCTT GCAGTC CGCCTC CCGCCG AGTGGG CCTCTC CTGTGC CAACTG CCAGAC CACCAC CACCAC GCTGTG GCGCCG CAATGC GGAGGG CGAGCC TGTGTG CAATGC CTGCGG CCTCTA CATGAA GCTCCA CGGGGT ACGTGG GTCCTG CGCCCA TGCGGC ATCCTT GCCTTC TGATGC CCATCT CTCAGT CCTCCC TTGTCT TCTTCC TTTGTA CTAGCA TTCATT TTTCCT TCTTAA CAAAGA GACTTA GATTTG GAAGGG GCTTTC AACTAC TTTGCT GGCCTC TTCCGT CCTTTA CATTGT ATAAGT GAATTT TCCGTT TTACAG ATGAGC AGGCTA CATTTA TATGTA GCAGTT TGATGT G T', '<cls> TATTCT CCAGGC TCTAGT AAAGTA GCCATC ACATCA CACAGG TGCTCG ATAAGT TTTTTA AAAATG GAATTG ATTTCT TTCTCG CTGAGT TCCAGG GGCCTG TGCAGC CCGTCT GGGCCC CAGGCT TTGTGG AGAGAT TGCTTA GGTGTT GCCTTC TCGCAG CAGGTG TGTGTC TTTCAA TGCTGT AGCAGA CTACGC AGAAAT GGAAAA CCCTAT ATATTT ACTTGT GACCCT CCAGGT CCCCAG GCCTCT TGCAAT GCGGAA AGAGGG GATCCA AACCAG AAAACG GAAGCC CAAGAA CCTGAA TAAATC TAAGAC ACCAGC AGGTGA GGAAAA GATCTG TGAGTG ATTATA TGAGTA CATCAG GAGCCC TCAGAG TGCCTA AGAATC ATATCT TCCGGG TTAGGC AGGCCA GCCCGG GCCGCC AGGGGG TGGTGA CAGCAT CGGACA TCCCTG GCCTTT CAGGAC AGGATG AAGAGC CCAGCA AAAAAG TAACAA TTGCCA TGGAAC G T', '<cls> TTCCTG GTTTGA CACCTT CCTTAG GAATGG ACATGG CTAAGA ATGCCA GACTTA ATCCCA TTTCTT CCCACA GAACAA GCACAG GCAATG TCTTTC TGACCC CCAGTG CCCCAC ACCCGG AGGCAG GAGAAA AGTTCT TACCTG TTGGAC CTGGTT AGGGAA GCCCCA ACCCCA GAATCC CTTCTT TCCGGG ATCTCG GAGGGC TCTTCC GGTTCA TTCAGG GAGTTG CCTGTG CTGTCC AGGTCG CTGGGT GTGGTT CGGTCG TTGTCC ACATCC AGGTGT ATCTGT TTTGGA GAGGAC GGGCAG GGAGAG ACCGAG TCCAGG GCTGAG TCCGAA TCTCCC TCATCA GAAAAC TTCTCC GACCAC TGATTG ACTATC CGCTGC ATCCCC TTCACG TGGTAG AGGATG TCGTCC AGCTCG GGGAAG ATGTCC TCGTTC TCCAGA TCCGCC AGGTCC CCTGAA CTGGAG TAGAGG ATGGAG CCCGGC ACGTTG TCGTAG ATGCTC AGGCGG C T', '<cls> ATGAAC ACATTG GATACC TGTATC CAAATA CCTGTT TGTTGT ACCTGT ATGTAC CATGAA CTGTTA AATGTA AGTATA CTGTAA TTGAAT GCATTT AAAAAT ATAAAC AATTGG GGTTTC ATTTGC ATATTT TTAGAC ACTAAT GGTATT TTCTGT CTGTTT CTAGTA ATTTGC CTAGTG GGATTG GGCCTG GTGGTC TTCTTC TTCAGT TTTCTA CTTTCA ATATTT CGTTCC AAGTAC CACGGC TATCCT TATAGG TAATAT CTTTAT ACTAAC ATGAAT GTTTTT ATTTTT AACTAA TAGAAC AGAGTT TCAGTG GTTAAT ATATAA TTAAGG ATGAAT GTAAAG TTGCTG TGTGGT TTTTTT AAATTC AGTTAA GCAAGT TTTTGA GCACCT GCCATG TGTTCA GCATAG TGAAGT ACACAA AGGAGA TATAAG GCATGG TTCTTG TTCCCT GACAGC ATGTAG TTTCTT TCTAGA CATACA TATTTT TATATA ACAAAT GAGGTT T A', '<cls> ATTTAA GTGATA CCAGGC TACTGG TTATCG TACCCT GTCTTT ATCTGA TTTTCA TATTCT TTCCTT TGGGTA TTTGCA GTAAAT GTAAGC TCAGAA ACTATT TATTTC AAACCA TAGGAT TTCAAA TATCAA ATCTCT GCATGT ATCAGT ATATTT TAATAT ATATAT CATTTT CTGGAG AAATGA CAAGAC ATTTTA CCTTGA ATTAAA GTGATA TTTCTC AAGGTC TGAGAA TGTTCC CAATCT TTCAGT CTGAGA TCATTA GTGATG TTATTC AGTACT TTCACT TCTCCT TTTATT TCCTGT TCCAAA TGCACT TGTTCT TCTTTC ATAGCC ATAATT TCTGCT GATACA TTGTAA ACACGC TCCTCT AATTTA CTGATT TCCTGT AAAACA TAAGTG AGCATT CACAGC CTTTGT TACATA CATAAT TATCAA ATATGA AAGTTC AAGAAA CCCTCG GAGTTC AGGTTT TTAAAA ACATAT TATGGG AGTTTT ATGGAA TAAGAA T A', '<cls> TCATGT CCCATT CAAAGT ATTATC TGCTCC TTGTAC CATTAG TGCTAA TGAAAT GAATTT GCTCAT AATTTG ATAATT TTAGCT ATTAGA TTATTA GCTATC TTCAAC ATTCAA AACATA AAATAA TGCCAA CAAGTT AAAAGC TTCCTG TCATAC TGTTGG AAGTAA AGTAGT AGGCAT ATCTTT GTAAAA GTGACT GGTATT TTCAAA AATTTA TTTTCT AGATTT GCCACT GTAGAA GAGCCA AGGAAG AGAAAC TTCAGC AGGCGA TAGCAA TGCACA GCCAAT TTCATG CTCCAC TATAGG TAAATT GTATTT CAAGTT TGAGTC TCAAGG TGATTG CATCAG TGTTCT TTAAAT AGACAT GTTGTT AACGGT GCCTGT TCATCA GCCTTA AGCATA ATTCTG TCATTA TAGTTA CTGTGC TATGTA ACATAG AATGCT TTGTAT TATATA ATAAGC ATAATA TAAACA TATAAC TAGTAG AAATCT TTTGGA TATTTT CTGTGA T C', '<cls> TAAAAA TACAAA AATGAG TTGGGT GTGGCG GCGGGC ACCTGT AATCTC AGCTAC TCAGGG TGCTCA GGCAAG AGAATC ACTTGA ACCTGG GAGGTG GAGGTT GCAGTG AGCTGA GATTAT GCCACT GCCCTC CAACCT GGGCAA TAGAGT AAGAAT CTGTCT CAAAAA AAAAAA AAAGTT ATTGGC CTCAAA TATTCC AAAAAT GTCATT ACTACA GCGCAT TTCTCT CTCCTT ACGTTT TGCAGT TACTGG CCAACA CCTTCC CAAGAA CAAGCG TCCAAA AGAACC AGGAGA GAATAG AATCAA ACCTAC CAACAA GAAGGT GAAGCC CAAAAT TCCTAA AATGAA GGACAG GGACTC AGCCAA TTCAGC ACCAAA GACGCA GTCTAT CATGAT GCAAGT GCTGGA TAAAGG TCGCTT CCAGAA ACCCGC CGCTAC CCTGAG TCTGCT GGCGGG GCAAAC TGTAGA GCTTCG ATGTAA AGGGAG TAGAAT TGGGTG GAGCTA CCCTGC G T', '<cls> CAATTT TGCTCT TTAAGT TAAGAA AACGAA ACAAAA AAATCA GTGGAG AGTGGC TAGAGA TACTAT GAAAAA TAGGAC GTTTAT AAATTA CTTGAA GGCCAA AGAAAA ATGCCA GAACCA AGGGAA TCTTTA ATGGCA ACAGTT TCTTTC TATAGA TGACCC TGCAAA GGTACC TCTTGG CTGGTG CGGTTC AGACAC ATCTTT GCAGGC GTTCTG CGATCA TCAAGG AAGAAG GGATGT TTCCAA CGGTCA TAATTT GTTTGT ACCACA TACCAT CTACCC TGCTTA GCATCG AGTCTA GATACA AAAGGA GAGATT CCCTCT TAGGCT ACATGC CTTAAA ACTCAA AGTATA TCAGTG TATGCT TTTGTT TCTACT TCTTTT GCTTTA ACAAAC CTACTT ACTCAT ATACAT CCAATG ATTCCT TTCTGT CTCGTG TAATCA CACAAC CTTCCC CAGACT GGTTGC CTCCCA GGATAA AGTAGG CTGGGG CCAATA TCTTGG TCTTGG T C', '<cls> TTTCAT AATGTC AGTATC CCTAGT GCTTTT TAAGTA ATTCAT TTATTT GCTATA AAACAC ACAGTC TGCACG AAGAAA ACATGA GTAATT CCACAT GAGTGT CAGAGG TTCACC TAAGAA ATTCTG CAATAG TTCCTC AAAGGA TTAAGC TGGAGC TTGACA AATATT TTTATT TTTTAA TATGAG TAATTT AAAATA AATATT TAATAG TAAAGC AACGAA ACACTT TACCTT GTGCTA TTTTCC AGAACT GTTCTA GTGAGG AACCCT ATCCAC ATGACA TCTTTC TTTCCC AGAATC CATTCT AGAATA CCTGGA AGAGAT GAACAC AATGTC AGGAAC CGGAAG AGGTGA CACTAT GTAACC AGTCAG GACCCG GAAGAG GCTGGA CTATAT AACCAG TCAGGA ACCAGA AGAGGT TAGACT TTGTAA CCAGTC GGGAAC CGGAAG AGGTTG GACTTT GTAACC AGAAGG CACAGT CCAGCC TTCCTC ATAAAA AAGCTC TGAGAT T C', '<cls> TTTCTT TCCCAG AATCCA TTCTAG AATACC TGGAAG AGATGA ACACAA TGTCAG GAACCG GAAGAG GTGACA CTATGT AACCAG TCAGGA CCCGGA AGAGGC TGGACT ATATAA CCAGTC AGGAAC CAGAAG AGGTTA GACTTT GTAACC AGTCGG GAACCG GAAGAG GTTGGA CTTTGT AACCAG AAGGCA CAGTCC AGCCTT CCTCAT AAAAAA GCTCTG AGATTC CCATTT CACTTG AGAATG CTCTAC TTACCC AGATAA CCACCA TTTATA CTGAAA CGTTCA TTCAGT GTAAGA CTGAAC AGTCCC TGAGAA AAAGAC AAAGCA ACGAAG TCAGAA ACATCA ACCATG CGCTTT AAGGCC CTGTCG CTCACT GTACTT CAGAGT GGGATA TAAAGG CCTAGC TTGGGT AATGGG GAAGGC AAAAAT AAATCA AAACCA TAAAAG GCTTTT TAAAAA GTTCAA AGCATT TTTGAT TCTAGT ATGTGA GATAAG TAGGTG GGGTAT C A', '<cls> ATGAAC ACAATG TCAGGA ACCGGA AGAGGT GACACT ATGTAA CCAGTC AGGACC CGGAAG AGGCTG GACTAT ATAACC AGTCAG GAACCA GAAGAG GTTAGA CTTTGT AACCAG TCGGGA ACCGGA AGAGGT TGGACT TTGTAA CCAGAA GGCACA GTCCAG CCTTCC TCATAA AAAAGC TCTGAG ATTCCC ATTTCA CTTGAG AATGCT CTACTT ACCCAG ATAACC ACCATT TATACT GAAACG TTCATT CAGTGT AAGACT GAACAG TCCCTG AGAAAA AGACAA AGCAAC GAAGTC AGAAAC ATCAAC CATGCG CTTTAA GGCCCT GTCGCT CACTGT ACTTCA GAGTGG GATATA AAGGCC TAGCTT GGGTAA TGGGGA AGGCAA AAATAA ATCAAA ACCATA AAAGGC TTTTTA AAAAGT TCAAAG CATTTT TGATTC TAGTAT GTGAGA TAAGTA GGTGGG GTATCA CTGGCA ACGCTT TTTGGA CAGGAA ACTGAA GGGCAG A G', '<cls> GATCTC ATACCT ATGAAG TGACAA GAAGTA CAAGGG GGTGAA ATGGGG CTTCAT ATTCCC TTTAGG TCCTCA TATTCT TAGATT TCAACT TTTACA TAACGG TAACAG GACAGA AGGCTA CCTGTA TAATTA TGTAAC AACAGA CTCCTT ACTGGT TTGAAT CCTGTT AACATG CCCACA TAGCCA GCAAAG CTTGAA GCCTTG AAGACA GTTTTG TTGTTT CTTTGG AAATCC AAATTC ACTGTT AAAGGT TTTAGT TGCTCA GTTATG ACCCAG GTATCA TTATTT ATGTTC CACCTA TAAAAG ACATGT TTCAGT GACATT TCAGAA ACACAG TGATAG TAATGA TCAACA TGATGA TGAGGG CCAGGC ATTACA CTAGGA GCTTTA TTTACC GAGTCA CCACGA TCAATC CTAACA AGACCT TTACAA TATGGT ATATTT ATTCTG TTTTCC AAAT

In [ ]:
# Method 2: map
def decode_batch(batch):
  return {"tokens": tokeniser.decode(batch["input_ids"])}

decoded = tokenised_dataset.map(decode_batch, batched=True, batch_size=64)
print(decoded)
print(decoded["tokens"])

Dataset({
    features: ['ref_forward_sequence', 'alt_forward_sequence', 'label', 'chromosome', 'position', 'seq', 'ref', 'alt', 'start', 'stop', 'chrom', 'input_ids', 'attention_mask', 'tokens'],
    num_rows: 1018
})
Column(['<cls> ACTGGG GTAGTG ATGTGT CCTTGT TTCTAT CGAGTC AACACA AAATGA ATGATC TTTCTT TTAGAT TGAAGA TGGATA CGTGAC AATCCC AGGGAC CGCTGC ACTGAC TTCATT TCCTTA GACAAG ACACAG TGTAGG GCCCGG CCCGTG TTGGCC CCAGGA CTCCTT TGGAAT ATAGCT GTGGAC AATGAA TCCTGC GAGCGA TGGGGG CACATC AGAGAG CATTTT TGACCT GGACTA TGCATC CTGGGG GATCCG CTCCAC GCTGAT GGTCGC TGGCTT TGTCTT CTACTT GGGCGT CTTTGT GGTCTG CCACCA GCTGTC CTCTTC CCTGAA TGCCAC TTACCG TTCTTT GGTGGC CAGAGA GAAGGT CTTCTG GGACCT GGCGGC CACGCG TGCAGT CTTTGG TGTTCA GAGCAC AGCCGC AGGCCT GTGGGC TCTGCT GGGGGA CCCTGT GCTGCA TGCCGA CAAGGC GCGTGG CCAGCA GAACTG GTGCTG GTTTCA CATCAC G A', '<cls> CCTTGT TTCTAT CGAGTC AACACA AAATGA ATGATC TTTCTT TTAGAT TGAAGA TGGATA CGTGAC AATCCC AGGGAC CGCTGC ACTGAC TTCATT TCCTTA GACAAG ACACAG TGTAGG GCCCGG CCCGTG TTGGCC CCAGGA CTCCTT TGGAAT ATAGCT GTGGAC AATGAA TCCTGC GAGCGA TGGGGG CACATC AGAGAG CATTTT TGACCT GGACTA TGCATC CTGGGG GATCCG CTCCAC GCTGAT GGTCGC TGGCTT TGTCTT CTACTT GGGCGT CTTTGT GGTCTG CCACCA GCTGTC CTCTTC CCTGAA TGCCAC TTACCG TTCTTT GGTGGC CAGAGA GAAGGT CTTCTG GGACCT GGCGGC CACGCG TGCAGT CTTTGG TGTTCA GAGCAC AGCCGC AGGCCT GTGGGC TCTGCT GGGGGA CCCTGT GCTGCA TGCCGA CAAGGC GCGTGG CCAGCA GAACTG GTGCTG GTTTCA CATCAC GACAGC AACGGG ATTCTT T T', '<cls> TCTCCA TGCAGG CGGGCT GGTCCG AGTCTC TGTTTT GGAAGC TCAACC AGTGGC TGATGA TTCACA TGTTTC ACTGCC GCATGG TTCTAA CCTACC ACATGT GGTGGG TGTGTT TCTGGC ACTGGG ACGGCC TGGTCA GCAGCC TGTATC TGCCTC ATTTGA CACTGT TCCTTG TCGGAC TGGCTC TGCTTA CGCTAA TCATTA ATCCAT ATTGGA CCCATA AGAAGA CTCAGC AGCTTC TCAATC CGGTGG ACTGGA ACTTCG CACAGC CAGAAG CCAAGA GCAGGC CAGAAG GCAACG GGCAGC TGCTGC GGAAGA AGAGGC CATAGC TGCTCC AGCCGG GGCTCC GGGGCG GCAGCA GAGCTG GCACAC CGATTC TGGGAA GCCCCG CGAATG ATGGCT TTTGAA TTAATG AGGCAG TGAATG TTTTGT GTTTAC TTCTAA GGGAAA TACTAA CTTTCT TTCGCA TTAGTA TTAATT TTGAAG TAGCTA CAAAGT ATTTTT AAGAAA T T', '<cls> GGGAAC ATGTTT CACCAT GTCCAG GAAGGG CTGTAT TTTTAA GGTCTG TTTTTT CCTTTT TTCCAA CAAACA AAACCA AAACAA AACCTA GCCCAG AACTGC ACGTGA CACATG CGCTCA CAAGAA CCAGAC TACTTG ACAGTA TTCTTT TAAAAC AGGCAA ATGAAA GTCGCA GGTGGG TTCTGC CGCCGT CCCGTT CTCACA TCTCCC TCTCCG TCGCAG ATGCAG AAGCTC GTGAAG GCCGCG AAGGAC GGCACC AAGGAC GGGCTG GAGAGG ACCAGG GCAGCC GTGAAG AGGGGC CGCTCC TTCATC AGGACC AAGTCT CTCATC GCACAG GGTCCG TGCCTG CAGGTC TTCTTG CGGGGA GGACAC GGGGTT GGGGGG GGCGGC CACATC TTGTGG GGAGGA CTCGGG GTGGGG GGCGGC CGCGCA GGCTCC CACAGC CTTAGG GAGCAC CAGCCT GCTCAG TGCTTG GGTCTG AATCAG CCCTGC TGACCC CAGCCT CCCCGT C C', '<cls> TAACAC TTCAGA GGGTTT TTAGAG GGAGTA GATGTG AACTTG TGTGTA TGATTC ACCGTT GTAACT GGAACA GATATG TTTTAA GCAGCG TTATGC ATTCCT TTGAGT GTTTCT CTGTCA GATGTT GAGAAA CAGAAT TGCTGG GGTAGA GGTTTT TTGATC AGTTGT AGTTAA GTTGTG AATGAA CAGTAA TGTACA TTTTGT TTTCTG CATTTT GTCTAC AGGTTT CAAAAA CTTTTA ACAAAC AAGTAA CTCACG TTATCT TCAAAG ATGGCT ACCAGA GCACTT GGGACA AAGCTC AGAAGA GAGGCG TAAAGC TCGTTT CGGTGC TCTGGG TGGAAA AGTAAG CAGTTT CTCTCT TACTTT TTTTCC TTAAGT ATCTAG TATTGA AAATGT GTGGAG ATATTT TTCACA GATCGC AGAACC AGATAA AGTTTG ATTTTC ATCTTT TCTCTG CCTCTT ACCTCA CCTAGT AATTTG AAATCC TCCAGC CTCAAT TTCTGT GGTTCA A A'])